#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
module Taoism
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 286)

attr_reader :errors

def initialize(lexer)
  @lexer = lexer
  @errors = []
end

def parse
  do_parse
end

def next_token
  tok = @lexer.next_token
  return nil if tok.type == TokenType::EOF
  [tok.type, tok]
end

def on_error(error_id, val, stack)
  tok = Array(val).first
  msg = if tok.respond_to?(:lexeme)
    "unexpected token #{tok.lexeme.inspect} at #{tok.start.line}:#{tok.start.col}"
  else
    "parse error"
  end
  @errors << msg
end

private

def parse_int(tok)
  tok.lexeme.delete('_').to_i
end

def parse_float(tok)
  tok.lexeme.delete('_').to_f
end

def parse_string(tok)
  tok.lexeme[1...-1]
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    50,    28,    31,    30,    29,    32,    33,   167,    23,   174,
   105,   165,   103,    62,    63,   104,   117,    72,    24,    71,
    41,     3,    25,   175,    73,   148,    40,    51,    34,    64,
    65,    66,    62,    63,    41,    44,   149,   147,    42,    45,
   133,    62,    63,    68,   144,   135,    43,   146,    52,    28,
    31,    30,    29,    32,    33,   166,    23,    58,    59,    60,
    61,    72,    56,    71,    57,    72,    24,    71,    73,    46,
    25,    48,    73,    49,    40,    53,    34,    54,    58,    59,
    60,    61,    41,    56,    55,    57,    42,    13,    12,    11,
    16,    15,    62,    63,    43,    28,    31,    30,    29,    32,
    33,    80,    23,    64,    65,    66,    28,    31,    30,    29,
    32,    33,    24,    23,    62,    63,    25,    64,    65,    66,
    40,    81,    34,    24,    62,    63,    82,    25,    41,    62,
    63,    40,    42,    34,   118,   104,    83,    68,    84,    41,
    43,    85,    52,    42,   101,   102,   105,   107,    68,   109,
   112,    43,    28,    31,    30,    29,    32,    33,   113,    23,
   112,   117,    55,    28,    31,    30,    29,    32,    33,    24,
    23,   119,   123,    25,   129,   130,   131,    40,   132,    34,
    24,   136,   155,   156,    25,    41,   157,   105,    40,    42,
    34,   159,   160,   105,    68,   117,    41,    43,   164,   105,
    42,   170,   173,   176,   112,    68,   180,   181,    43,    28,
    31,    30,    29,    32,    33,   182,    23,   183,   105,   nil,
    28,    31,    30,    29,    32,    33,    24,    23,   nil,   nil,
    25,   nil,   nil,   nil,    40,   nil,    34,    24,   nil,   nil,
   nil,    25,    41,   nil,   nil,    40,    42,    34,   nil,   nil,
   nil,    68,   nil,    41,    43,   nil,   nil,    42,   nil,   nil,
   nil,   nil,    68,   nil,   nil,    43,    28,    31,    30,    29,
    32,    33,   nil,    23,   nil,   nil,   nil,    28,    31,    30,
    29,    32,    33,    24,   nil,   nil,   nil,    25,   nil,   nil,
   nil,    40,   nil,    34,   nil,   nil,   nil,   nil,   nil,    41,
   nil,   nil,    40,    42,    34,   nil,   nil,   nil,    68,   nil,
    41,    43,   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,
   nil,   nil,    43,    28,    31,    30,    29,    32,    33,   nil,
    23,   nil,   nil,   nil,    28,    31,    30,    29,    32,    33,
    24,    23,   nil,   nil,    25,   nil,   nil,   nil,    40,   nil,
    34,    24,   nil,   nil,   nil,    25,    41,   nil,   nil,    40,
    42,    34,   nil,   nil,   nil,    68,   nil,    41,    43,   nil,
   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,
    28,    31,    30,    29,    32,    33,   nil,    23,   nil,   nil,
   nil,    28,    31,    30,    29,    32,    33,    24,    23,   nil,
   nil,    25,   nil,   nil,   nil,    40,   nil,    34,    24,   nil,
   nil,   nil,    25,    41,   nil,   nil,    40,    42,    34,   nil,
   nil,   nil,    68,   nil,    41,    43,   nil,   nil,    42,   nil,
   nil,   nil,   nil,    68,   nil,   nil,    43,    28,    31,    30,
    29,    32,    33,   nil,    23,   nil,   nil,   nil,    28,    31,
    30,    29,    32,    33,    24,    23,   nil,   nil,    25,   nil,
   nil,   nil,    40,   nil,    34,    24,   nil,   nil,   nil,    25,
    41,   nil,   nil,    40,    42,    34,   nil,   nil,   nil,    68,
   nil,    41,    43,   nil,   nil,    42,   nil,   nil,   nil,   nil,
    68,   nil,   nil,    43,    28,    31,    30,    29,    32,    33,
   nil,    23,   nil,   nil,   nil,    28,    31,    30,    29,    32,
    33,    24,    23,   nil,   nil,    25,   nil,   nil,   nil,    40,
   nil,    34,    24,   nil,   nil,   nil,    25,    41,   nil,   nil,
    40,    42,    34,   nil,   nil,   nil,    68,   nil,    41,    43,
   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,
    43,    28,    31,    30,    29,    32,    33,   nil,    23,   nil,
   nil,   nil,    28,    31,    30,    29,    32,    33,    24,    23,
   nil,   nil,    25,   nil,   nil,   nil,    40,   nil,    34,    24,
   nil,   nil,   nil,    25,    41,   nil,   nil,    40,    42,    34,
   nil,   nil,   nil,    68,   nil,    41,    43,   nil,   nil,    42,
   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,    28,    31,
    30,    29,    32,    33,   nil,    23,   nil,   nil,   nil,    28,
    31,    30,    29,    32,    33,    24,    23,   nil,   nil,    25,
   nil,   nil,   nil,    40,   nil,    34,    24,   nil,   nil,   nil,
    25,    41,   nil,   nil,    40,    42,    34,   nil,   nil,   nil,
    68,   nil,    41,    43,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    68,   nil,   nil,    43,    28,    31,    30,    29,    32,
    33,   nil,    23,   nil,   nil,   nil,    28,    31,    30,    29,
    32,    33,    24,    23,   nil,   nil,    25,   nil,   nil,   nil,
    40,   nil,    34,    24,   nil,   nil,   nil,    25,    41,   nil,
   nil,    40,    42,    34,   nil,   nil,   nil,    68,   nil,    41,
    43,   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,
   nil,    43,    28,    31,    30,    29,    32,    33,   nil,    23,
   nil,   nil,   nil,    28,    31,    30,    29,    32,    33,    24,
    23,   nil,   nil,    25,   nil,   nil,   nil,    40,   nil,    34,
    24,   nil,   nil,   nil,    25,    41,   nil,   nil,    40,    42,
    34,   nil,   nil,   nil,    68,   nil,    41,    43,   nil,   nil,
    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,    28,
    31,    30,    29,    32,    33,   nil,    23,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
    25,   nil,   nil,   nil,    40,   nil,    34,   nil,   nil,   nil,
   nil,   nil,    41,   nil,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    68,   nil,   nil,    43,    28,    31,    30,    29,    32,
    33,   nil,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    24,   nil,   nil,   nil,    25,   nil,   nil,   nil,
    40,   nil,    34,   nil,   nil,   nil,   nil,   nil,    41,   128,
   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,
    43,    28,    31,    30,    29,    32,    33,   nil,    23,   nil,
   nil,   nil,    28,    31,    30,    29,    32,    33,    24,    23,
   nil,   nil,    25,   nil,   nil,   152,    40,   nil,    34,    24,
   nil,   nil,   nil,    25,    41,   128,   nil,    40,    42,    34,
   nil,   nil,   nil,    68,   nil,    41,    43,   nil,   nil,    42,
   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,    28,    31,
    30,    29,    32,    33,   nil,    23,   nil,   nil,   nil,    28,
    31,    30,    29,    32,    33,    24,    23,   nil,   nil,    25,
   nil,   nil,   nil,    40,   nil,    34,    24,   nil,   nil,   nil,
    25,    41,   nil,   nil,    40,    42,    34,   nil,   nil,   nil,
    68,   nil,    41,    43,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    68,   nil,   nil,    43,    28,    31,    30,    29,    32,
    33,   nil,    23,   nil,   nil,   nil,    28,    31,    30,    29,
    32,    33,    24,    23,   nil,   nil,    25,   nil,   nil,   nil,
    40,   nil,    34,    24,   nil,   nil,   nil,    25,    41,   nil,
   nil,    40,    42,    34,   nil,   nil,   nil,    68,   nil,    41,
    43,   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,
   nil,    43,    28,    31,    30,    29,    32,    33,   nil,    23,
   nil,   nil,   nil,    28,    31,    30,    29,    32,    33,    24,
    23,   nil,   nil,    25,   nil,   nil,   nil,    40,   nil,    34,
    24,   nil,   nil,   nil,    25,    41,   nil,   nil,    40,    42,
    34,   nil,   nil,   nil,    68,   nil,    41,    43,   nil,   nil,
    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,    28,
    31,    30,    29,    32,    33,   nil,    23,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
    25,   nil,   nil,   nil,    40,   nil,    34,   nil,   nil,   nil,
   nil,   nil,    41,   nil,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    68,   nil,   nil,    43 ]

racc_action_check = [
    15,   121,   121,   121,   121,   121,   121,   145,   121,   165,
   123,   144,    75,    20,    20,    75,   115,   145,   121,   145,
   123,     1,   121,   165,   145,   121,   121,    15,   121,    21,
    21,    21,    88,    88,   121,     3,   121,   121,   121,     4,
   115,    89,    89,   121,   121,   115,   121,   121,    15,     2,
     2,     2,     2,     2,     2,   144,     2,    19,    19,    19,
    19,    26,    19,    26,    19,    79,     2,    79,    26,    11,
     2,    12,    79,    13,     2,    16,     2,    17,    87,    87,
    87,    87,     2,    87,    18,    87,     2,     2,     2,     2,
     2,     2,    90,    90,     2,    23,    23,    23,    23,    23,
    23,    46,    23,    94,    94,    94,    24,    24,    24,    24,
    24,    24,    23,    24,    91,    91,    23,    95,    95,    95,
    23,    47,    23,    24,    92,    92,    50,    24,    23,    93,
    93,    24,    23,    24,    99,    99,    51,    23,    52,    24,
    23,    53,    68,    24,    73,    74,    77,    78,    24,    81,
    82,    24,    25,    25,    25,    25,    25,    25,    83,    25,
    84,    85,    86,    34,    34,    34,    34,    34,    34,    25,
    34,   100,   106,    25,   110,   111,   113,    25,   114,    25,
    34,   117,   125,   127,    34,    25,   128,   129,    34,    25,
    34,   130,   131,   132,    25,   135,    34,    25,   137,   149,
    34,   153,   160,   166,   173,    34,   175,   176,    34,    40,
    40,    40,    40,    40,    40,   178,    40,   180,   182,   nil,
    41,    41,    41,    41,    41,    41,    40,    41,   nil,   nil,
    40,   nil,   nil,   nil,    40,   nil,    40,    41,   nil,   nil,
   nil,    41,    40,   nil,   nil,    41,    40,    41,   nil,   nil,
   nil,    40,   nil,    41,    40,   nil,   nil,    41,   nil,   nil,
   nil,   nil,    41,   nil,   nil,    41,    42,    42,    42,    42,
    42,    42,   nil,    42,   nil,   nil,   nil,    43,    43,    43,
    43,    43,    43,    42,   nil,   nil,   nil,    42,   nil,   nil,
   nil,    42,   nil,    42,   nil,   nil,   nil,   nil,   nil,    42,
   nil,   nil,    43,    42,    43,   nil,   nil,   nil,    42,   nil,
    43,    42,   nil,   nil,    43,   nil,   nil,   nil,   nil,    43,
   nil,   nil,    43,    54,    54,    54,    54,    54,    54,   nil,
    54,   nil,   nil,   nil,    55,    55,    55,    55,    55,    55,
    54,    55,   nil,   nil,    54,   nil,   nil,   nil,    54,   nil,
    54,    55,   nil,   nil,   nil,    55,    54,   nil,   nil,    55,
    54,    55,   nil,   nil,   nil,    54,   nil,    55,    54,   nil,
   nil,    55,   nil,   nil,   nil,   nil,    55,   nil,   nil,    55,
    56,    56,    56,    56,    56,    56,   nil,    56,   nil,   nil,
   nil,    57,    57,    57,    57,    57,    57,    56,    57,   nil,
   nil,    56,   nil,   nil,   nil,    56,   nil,    56,    57,   nil,
   nil,   nil,    57,    56,   nil,   nil,    57,    56,    57,   nil,
   nil,   nil,    56,   nil,    57,    56,   nil,   nil,    57,   nil,
   nil,   nil,   nil,    57,   nil,   nil,    57,    58,    58,    58,
    58,    58,    58,   nil,    58,   nil,   nil,   nil,    59,    59,
    59,    59,    59,    59,    58,    59,   nil,   nil,    58,   nil,
   nil,   nil,    58,   nil,    58,    59,   nil,   nil,   nil,    59,
    58,   nil,   nil,    59,    58,    59,   nil,   nil,   nil,    58,
   nil,    59,    58,   nil,   nil,    59,   nil,   nil,   nil,   nil,
    59,   nil,   nil,    59,    60,    60,    60,    60,    60,    60,
   nil,    60,   nil,   nil,   nil,    61,    61,    61,    61,    61,
    61,    60,    61,   nil,   nil,    60,   nil,   nil,   nil,    60,
   nil,    60,    61,   nil,   nil,   nil,    61,    60,   nil,   nil,
    61,    60,    61,   nil,   nil,   nil,    60,   nil,    61,    60,
   nil,   nil,    61,   nil,   nil,   nil,   nil,    61,   nil,   nil,
    61,    62,    62,    62,    62,    62,    62,   nil,    62,   nil,
   nil,   nil,    63,    63,    63,    63,    63,    63,    62,    63,
   nil,   nil,    62,   nil,   nil,   nil,    62,   nil,    62,    63,
   nil,   nil,   nil,    63,    62,   nil,   nil,    63,    62,    63,
   nil,   nil,   nil,    62,   nil,    63,    62,   nil,   nil,    63,
   nil,   nil,   nil,   nil,    63,   nil,   nil,    63,    64,    64,
    64,    64,    64,    64,   nil,    64,   nil,   nil,   nil,    65,
    65,    65,    65,    65,    65,    64,    65,   nil,   nil,    64,
   nil,   nil,   nil,    64,   nil,    64,    65,   nil,   nil,   nil,
    65,    64,   nil,   nil,    65,    64,    65,   nil,   nil,   nil,
    64,   nil,    65,    64,   nil,   nil,    65,   nil,   nil,   nil,
   nil,    65,   nil,   nil,    65,    66,    66,    66,    66,    66,
    66,   nil,    66,   nil,   nil,   nil,    71,    71,    71,    71,
    71,    71,    66,    71,   nil,   nil,    66,   nil,   nil,   nil,
    66,   nil,    66,    71,   nil,   nil,   nil,    71,    66,   nil,
   nil,    71,    66,    71,   nil,   nil,   nil,    66,   nil,    71,
    66,   nil,   nil,    71,   nil,   nil,   nil,   nil,    71,   nil,
   nil,    71,    72,    72,    72,    72,    72,    72,   nil,    72,
   nil,   nil,   nil,    80,    80,    80,    80,    80,    80,    72,
    80,   nil,   nil,    72,   nil,   nil,   nil,    72,   nil,    72,
    80,   nil,   nil,   nil,    80,    72,   nil,   nil,    80,    72,
    80,   nil,   nil,   nil,    72,   nil,    80,    72,   nil,   nil,
    80,   nil,   nil,   nil,   nil,    80,   nil,   nil,    80,   104,
   104,   104,   104,   104,   104,   nil,   104,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   104,   nil,   nil,   nil,
   104,   nil,   nil,   nil,   104,   nil,   104,   nil,   nil,   nil,
   nil,   nil,   104,   nil,   nil,   nil,   104,   nil,   nil,   nil,
   nil,   104,   nil,   nil,   104,   107,   107,   107,   107,   107,
   107,   nil,   107,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   107,   nil,   nil,   nil,   107,   nil,   nil,   nil,
   107,   nil,   107,   nil,   nil,   nil,   nil,   nil,   107,   107,
   nil,   nil,   107,   nil,   nil,   nil,   nil,   107,   nil,   nil,
   107,   124,   124,   124,   124,   124,   124,   nil,   124,   nil,
   nil,   nil,   136,   136,   136,   136,   136,   136,   124,   136,
   nil,   nil,   124,   nil,   nil,   124,   124,   nil,   124,   136,
   nil,   nil,   nil,   136,   124,   124,   nil,   136,   124,   136,
   nil,   nil,   nil,   124,   nil,   136,   124,   nil,   nil,   136,
   nil,   nil,   nil,   nil,   136,   nil,   nil,   136,   146,   146,
   146,   146,   146,   146,   nil,   146,   nil,   nil,   nil,   156,
   156,   156,   156,   156,   156,   146,   156,   nil,   nil,   146,
   nil,   nil,   nil,   146,   nil,   146,   156,   nil,   nil,   nil,
   156,   146,   nil,   nil,   156,   146,   156,   nil,   nil,   nil,
   146,   nil,   156,   146,   nil,   nil,   156,   nil,   nil,   nil,
   nil,   156,   nil,   nil,   156,   157,   157,   157,   157,   157,
   157,   nil,   157,   nil,   nil,   nil,   167,   167,   167,   167,
   167,   167,   157,   167,   nil,   nil,   157,   nil,   nil,   nil,
   157,   nil,   157,   167,   nil,   nil,   nil,   167,   157,   nil,
   nil,   167,   157,   167,   nil,   nil,   nil,   157,   nil,   167,
   157,   nil,   nil,   167,   nil,   nil,   nil,   nil,   167,   nil,
   nil,   167,   174,   174,   174,   174,   174,   174,   nil,   174,
   nil,   nil,   nil,   181,   181,   181,   181,   181,   181,   174,
   181,   nil,   nil,   174,   nil,   nil,   nil,   174,   nil,   174,
   181,   nil,   nil,   nil,   181,   174,   nil,   nil,   181,   174,
   181,   nil,   nil,   nil,   174,   nil,   181,   174,   nil,   nil,
   181,   nil,   nil,   nil,   nil,   181,   nil,   nil,   181,   183,
   183,   183,   183,   183,   183,   nil,   183,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   183,   nil,   nil,   nil,
   183,   nil,   nil,   nil,   183,   nil,   183,   nil,   nil,   nil,
   nil,   nil,   183,   nil,   nil,   nil,   183,   nil,   nil,   nil,
   nil,   183,   nil,   nil,   183 ]

racc_action_pointer = [
   nil,    21,    46,    35,     5,   nil,   nil,   nil,   nil,   nil,
   nil,    66,    68,    70,   nil,    -3,    72,    54,    62,    43,
     4,    18,   nil,    92,   103,   149,    33,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   160,   nil,   nil,   nil,   nil,   nil,
   206,   217,   263,   274,   nil,   nil,    83,    86,   nil,   nil,
    96,   133,   108,   115,   320,   331,   377,   388,   434,   445,
   491,   502,   548,   559,   605,   616,   662,   nil,    91,   nil,
   nil,   673,   719,   141,   114,   -17,   nil,   120,   121,    37,
   730,   146,   147,   155,   157,   158,   140,    64,    23,    32,
    83,   105,   115,   120,    92,   106,   nil,   nil,   nil,   103,
   142,   nil,   nil,   nil,   776,   nil,   135,   822,   nil,   nil,
   143,   143,   nil,   145,   147,    13,   nil,   163,   nil,   nil,
   nil,    -2,   nil,   -16,   868,   155,   nil,   133,   136,   161,
   188,   189,   167,   nil,   nil,   192,   879,   164,   nil,   nil,
   nil,   nil,   nil,   nil,     8,   -11,   925,   nil,   nil,   173,
   nil,   nil,   nil,   174,   nil,   nil,   936,   982,   nil,   nil,
   172,   nil,   nil,   nil,   nil,    -9,   200,   993,   nil,   nil,
   nil,   nil,   nil,   201,  1039,   203,   189,   nil,   184,   nil,
   199,  1050,   192,  1096,   nil,   nil,   nil ]

racc_action_default = [
    -2,  -103,    -1,  -103,    -3,    -5,    -6,    -7,    -8,    -9,
   -10,  -103,  -103,  -103,   -31,  -103,  -103,   -46,   -47,   -49,
   -51,   -58,   -61,  -103,  -103,  -103,   -68,   -69,   -70,   -74,
   -75,   -76,   -77,   -78,  -103,   -80,   -81,   -82,   -83,   -84,
   -86,  -103,  -103,  -103,   187,    -4,  -103,   -25,   -27,   -26,
  -103,  -103,  -103,  -103,  -103,  -103,  -103,  -103,  -103,  -103,
  -103,  -103,  -103,  -103,  -103,  -103,  -103,   -65,  -103,   -66,
   -67,   -86,  -103,  -103,  -103,  -103,   -87,  -103,  -103,  -101,
  -103,  -103,   -34,  -103,   -34,   -39,   -48,   -50,   -52,   -53,
   -54,   -55,   -56,   -57,   -59,   -60,   -62,   -63,   -64,  -103,
  -103,   -73,   -79,   -85,  -103,   -11,   -92,  -103,   -24,   -28,
  -103,   -35,   -36,  -103,  -103,  -103,   -40,   -43,   -71,   -72,
   -88,  -103,   -89,  -103,  -103,  -103,   -97,  -103,  -103,  -103,
  -103,  -103,  -103,   -38,   -41,  -103,  -103,   -12,   -14,   -15,
   -16,   -17,   -18,   -19,  -103,   -68,  -103,   -30,   -45,  -103,
   -90,   -91,   -94,  -103,   -98,   -96,  -103,  -103,   -32,   -37,
  -103,  -102,   -42,   -44,   -13,  -103,  -103,  -103,   -29,   -93,
   -95,   -99,  -100,   -34,  -103,  -103,  -103,   -23,  -103,   -20,
  -103,  -103,  -103,  -103,   -21,   -33,   -22 ]

racc_goto_table = [
    74,    10,   106,   110,    79,   114,    76,    77,    78,   116,
    67,    69,    70,    75,   125,   126,    88,    89,    90,    91,
    92,    93,    94,    95,     1,     2,     4,     5,     6,     7,
     8,   153,   154,     9,   121,   137,   138,    76,   100,   134,
   139,   140,   141,   142,    99,    47,   108,   115,   150,    86,
    87,    96,    97,    98,   158,   151,   122,   161,   124,   162,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   120,   nil,   nil,   127,   169,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   145,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   127,   nil,   nil,   nil,   178,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   163,   nil,   nil,   nil,   nil,   185,   nil,   nil,
   nil,   nil,   168,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   143,   nil,   171,   172,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   177,   nil,   nil,   nil,   nil,   nil,   nil,
   179,   nil,   nil,   nil,   nil,   nil,   nil,   184,   nil,   186 ]

racc_goto_check = [
    17,     9,    21,    20,    18,    20,    17,    17,    17,    24,
    30,    30,    30,    32,    40,    41,    28,    28,    28,    28,
    28,    28,    29,    29,     1,     2,     3,     4,     5,     6,
     7,    40,    41,     8,    10,    11,    12,    17,    17,    24,
    13,    14,    15,    16,    32,    19,    17,    23,    21,    26,
    27,    30,    30,    30,    21,    34,    38,    21,    39,    24,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    17,   nil,   nil,    17,    21,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    17,   nil,   nil,   nil,    20,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    17,   nil,   nil,   nil,   nil,    21,   nil,   nil,
   nil,   nil,    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     9,   nil,    17,    17,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    17,   nil,   nil,   nil,   nil,   nil,   nil,
    17,   nil,   nil,   nil,   nil,   nil,   nil,    17,   nil,    17 ]

racc_goto_pointer = [
   nil,    24,    25,    24,    25,    26,    27,    28,    31,    -1,
   -71,   -86,   -85,   -81,   -80,   -79,   -78,   -34,   -39,    33,
   -79,   -75,   nil,   -38,   -76,   nil,    -5,    -5,   -40,   -40,
   -13,   nil,   -27,   nil,   -68,   nil,   nil,   nil,   -50,   -49,
   -93,   -92 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,    26,   nil,
   nil,   nil,   111,   nil,   nil,    17,    18,    19,    20,    21,
    22,    27,   nil,    35,    36,    37,    38,    39,   nil,   nil,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 55, :_reduce_1,
  0, 56, :_reduce_2,
  2, 56, :_reduce_3,
  3, 56, :_reduce_4,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  0, 64, :_reduce_11,
  2, 64, :_reduce_12,
  3, 64, :_reduce_13,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  4, 66, :_reduce_20,
  5, 66, :_reduce_21,
  6, 66, :_reduce_22,
  3, 67, :_reduce_23,
  4, 58, :_reduce_24,
  2, 61, :_reduce_25,
  2, 62, :_reduce_26,
  1, 73, :_reduce_27,
  3, 73, :_reduce_28,
  2, 68, :_reduce_29,
  1, 69, :_reduce_30,
  1, 63, :_reduce_31,
  6, 59, :_reduce_32,
  10, 59, :_reduce_33,
  0, 74, :_reduce_34,
  1, 74, :_reduce_35,
  1, 76, :_reduce_36,
  3, 76, :_reduce_37,
  5, 60, :_reduce_38,
  0, 77, :_reduce_39,
  1, 77, :_reduce_40,
  2, 77, :_reduce_41,
  3, 77, :_reduce_42,
  1, 78, :_reduce_43,
  3, 78, :_reduce_44,
  3, 75, :_reduce_45,
  1, 71, :_reduce_46,
  1, 79, :_reduce_none,
  3, 79, :_reduce_48,
  1, 80, :_reduce_none,
  3, 80, :_reduce_50,
  1, 81, :_reduce_none,
  3, 81, :_reduce_52,
  3, 81, :_reduce_53,
  3, 81, :_reduce_54,
  3, 81, :_reduce_55,
  3, 81, :_reduce_56,
  3, 81, :_reduce_57,
  1, 82, :_reduce_none,
  3, 82, :_reduce_59,
  3, 82, :_reduce_60,
  1, 83, :_reduce_none,
  3, 83, :_reduce_62,
  3, 83, :_reduce_63,
  3, 83, :_reduce_64,
  2, 84, :_reduce_65,
  2, 84, :_reduce_66,
  2, 84, :_reduce_67,
  1, 84, :_reduce_none,
  1, 72, :_reduce_none,
  1, 72, :_reduce_70,
  4, 72, :_reduce_71,
  4, 72, :_reduce_72,
  3, 72, :_reduce_73,
  1, 85, :_reduce_74,
  1, 85, :_reduce_75,
  1, 85, :_reduce_76,
  1, 85, :_reduce_77,
  1, 85, :_reduce_78,
  3, 85, :_reduce_79,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  3, 87, :_reduce_85,
  0, 86, :_reduce_86,
  1, 86, :_reduce_87,
  3, 86, :_reduce_88,
  4, 88, :_reduce_89,
  2, 92, :_reduce_90,
  2, 92, :_reduce_91,
  0, 92, :_reduce_92,
  2, 70, :_reduce_93,
  5, 89, :_reduce_94,
  6, 89, :_reduce_95,
  5, 89, :_reduce_96,
  1, 93, :_reduce_97,
  2, 93, :_reduce_98,
  3, 95, :_reduce_99,
  3, 94, :_reduce_100,
  2, 90, :_reduce_101,
  6, 91, :_reduce_102 ]

racc_reduce_n = 103

racc_shift_n = 187

racc_token_table = {
  false => 0,
  :error => 1,
  :ILLEGAL => 2,
  :IDENTIFIER => 3,
  :STRING => 4,
  :FLOAT => 5,
  :INT => 6,
  :BOOL => 7,
  :NONE => 8,
  :PLUS => 9,
  :MINUS => 10,
  :STAR => 11,
  :SLASH => 12,
  :MODULO => 13,
  :GREATER => 14,
  :GREATEREQ => 15,
  :LESS => 16,
  :LESSEQ => 17,
  :EQUAL => 18,
  :EQUALEQ => 19,
  :BANG => 20,
  :BANGEQ => 21,
  :AND => 22,
  :OR => 23,
  :NOT => 24,
  :PIPE => 25,
  :LBRACE => 26,
  :RBRACE => 27,
  :LSQUARE => 28,
  :RSQUARE => 29,
  :LPAREN => 30,
  :RPAREN => 31,
  :COMMA => 32,
  :COLON => 33,
  :SEMI => 34,
  :DOT => 35,
  :IF => 36,
  :ELSE => 37,
  :LOOP => 38,
  :LEAVE => 39,
  :SWITCH => 40,
  :PACKAGE => 41,
  :IMPORT => 42,
  :CONST => 43,
  :DATA => 44,
  :FUN => 45,
  :LET => 46,
  :MUT => 47,
  :TRY => 48,
  :RETURN => 49,
  :EQARROW => 50,
  :ARROW => 51,
  :EOF => 52,
  :UMINUS => 53 }

racc_nt_base = 54

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "ILLEGAL",
  "IDENTIFIER",
  "STRING",
  "FLOAT",
  "INT",
  "BOOL",
  "NONE",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "MODULO",
  "GREATER",
  "GREATEREQ",
  "LESS",
  "LESSEQ",
  "EQUAL",
  "EQUALEQ",
  "BANG",
  "BANGEQ",
  "AND",
  "OR",
  "NOT",
  "PIPE",
  "LBRACE",
  "RBRACE",
  "LSQUARE",
  "RSQUARE",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "COLON",
  "SEMI",
  "DOT",
  "IF",
  "ELSE",
  "LOOP",
  "LEAVE",
  "SWITCH",
  "PACKAGE",
  "IMPORT",
  "CONST",
  "DATA",
  "FUN",
  "LET",
  "MUT",
  "TRY",
  "RETURN",
  "EQARROW",
  "ARROW",
  "EOF",
  "UMINUS",
  "$start",
  "program",
  "top_stmts",
  "top_stmt",
  "const_stmt",
  "fun_def",
  "data_def",
  "import_stmt",
  "package_stmt",
  "expr_stmt",
  "block_stmts",
  "block_stmt",
  "let_stmt",
  "assign_stmt",
  "return_stmt",
  "leave_stmt",
  "loop_stmt",
  "expr",
  "postfix_expr",
  "path",
  "params",
  "block",
  "param_list",
  "field_list",
  "field",
  "or_expr",
  "and_expr",
  "cmp_expr",
  "add_expr",
  "mul_expr",
  "unary_expr",
  "primary",
  "args",
  "list_lit",
  "if_expr",
  "switch_expr",
  "try_expr",
  "fun_lit",
  "else_clause",
  "switch_body",
  "else_arm",
  "switch_arm" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_1(val, _values, result)
          first = val[0].first
      last  = val[0].last
      result = Nodes::Program.new(val[0],
        first ? first.start : nil,
        last  ? last.end   : nil)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_2(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_3(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_4(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_11(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_12(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_13(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_20(val, _values, result)
     result = Nodes::Let.new(val[1].lexeme, val[3], false,
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_21(val, _values, result)
     result = Nodes::Let.new(val[2].lexeme, val[4], true,
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_22(val, _values, result)
     result = Nodes::LetPair.new(val[1].lexeme, val[3].lexeme, val[5],
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_23(val, _values, result)
     result = Nodes::Assign.new(val[0], val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_24(val, _values, result)
     result = Nodes::Const.new(val[1].lexeme, val[3],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_25(val, _values, result)
     result = Nodes::Import.new(val[1][0],
        val[0].start, val[1][1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_26(val, _values, result)
     result = Nodes::Package.new(val[1].lexeme,
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 88)
  def _reduce_27(val, _values, result)
     result = [val[0].lexeme, val[0].end]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_28(val, _values, result)
     result = [val[0][0] + '.' + val[2].lexeme, val[2].end]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 92)
  def _reduce_29(val, _values, result)
     result = Nodes::Return.new(val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_30(val, _values, result)
     result = Nodes::Leave.new(val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_31(val, _values, result)
     result = Nodes::ExprStmt.new(val[0],
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 103)
  def _reduce_32(val, _values, result)
     result = Nodes::FunDef.new(val[1].lexeme, val[3], val[5], nil,
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 107)
  def _reduce_33(val, _values, result)
     result = Nodes::FunDef.new(val[5].lexeme, val[7], val[9],
        Nodes::Receiver.new(val[2].lexeme, val[3].lexeme,
          val[1].start, val[4].end),
        val[0].start, val[9].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 112)
  def _reduce_34(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 113)
  def _reduce_35(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_36(val, _values, result)
     result = [val[0].lexeme]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_37(val, _values, result)
     val[0] << val[2].lexeme; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 119)
  def _reduce_38(val, _values, result)
     result = Nodes::DataDef.new(val[1].lexeme, val[3],
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 122)
  def _reduce_39(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_40(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 124)
  def _reduce_41(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 125)
  def _reduce_42(val, _values, result)
     val[0] << val[2]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 128)
  def _reduce_43(val, _values, result)
     result = Nodes::Field.new(val[0].lexeme, nil,
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 131)
  def _reduce_44(val, _values, result)
     result = Nodes::Field.new(val[0].lexeme, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 135)
  def _reduce_45(val, _values, result)
     result = Nodes::Block.new(val[1],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 138)
  def _reduce_46(val, _values, result)
     result = val[0]
    result
  end
.,.,

# reduce 47 omitted

module_eval(<<'.,.,', 'parser.y', 142)
  def _reduce_48(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :or, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 49 omitted

module_eval(<<'.,.,', 'parser.y', 147)
  def _reduce_50(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :and, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 51 omitted

module_eval(<<'.,.,', 'parser.y', 152)
  def _reduce_52(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'==', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 155)
  def _reduce_53(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'!=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 158)
  def _reduce_54(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'>', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 161)
  def _reduce_55(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'>=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 164)
  def _reduce_56(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'<', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 167)
  def _reduce_57(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'<=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 58 omitted

module_eval(<<'.,.,', 'parser.y', 172)
  def _reduce_59(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'+', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 175)
  def _reduce_60(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'-', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 61 omitted

module_eval(<<'.,.,', 'parser.y', 180)
  def _reduce_62(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'*', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 183)
  def _reduce_63(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'/', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 186)
  def _reduce_64(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'%', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 190)
  def _reduce_65(val, _values, result)
     result = Nodes::UnaryOp.new(:'-', val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 193)
  def _reduce_66(val, _values, result)
     result = Nodes::UnaryOp.new(:'!', val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 196)
  def _reduce_67(val, _values, result)
     result = Nodes::UnaryOp.new(:'!', val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

# reduce 68 omitted

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.y', 202)
  def _reduce_70(val, _values, result)
     result = Nodes::Identifier.new(val[0].lexeme,
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 205)
  def _reduce_71(val, _values, result)
     result = Nodes::Call.new(val[0], val[2],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 208)
  def _reduce_72(val, _values, result)
     result = Nodes::Index.new(val[0], val[2],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 211)
  def _reduce_73(val, _values, result)
     result = Nodes::DotExpr.new(val[0], val[2].lexeme,
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 215)
  def _reduce_74(val, _values, result)
     result = Nodes::IntLit.new(parse_int(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 218)
  def _reduce_75(val, _values, result)
     result = Nodes::FloatLit.new(parse_float(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 221)
  def _reduce_76(val, _values, result)
     result = Nodes::StringLit.new(parse_string(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 224)
  def _reduce_77(val, _values, result)
     result = Nodes::BoolLit.new(val[0].lexeme == 'True',
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 227)
  def _reduce_78(val, _values, result)
     result = Nodes::NoneLit.new(val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 229)
  def _reduce_79(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

module_eval(<<'.,.,', 'parser.y', 237)
  def _reduce_85(val, _values, result)
     result = Nodes::ListLit.new(val[1],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 240)
  def _reduce_86(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 241)
  def _reduce_87(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 242)
  def _reduce_88(val, _values, result)
     val[0] << val[2]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 245)
  def _reduce_89(val, _values, result)
     result = Nodes::If.new(val[1], val[2], val[3],
        val[0].start, val[3] ? val[3].end : val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 248)
  def _reduce_90(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 249)
  def _reduce_91(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 250)
  def _reduce_92(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 253)
  def _reduce_93(val, _values, result)
     result = Nodes::Loop.new(val[1], val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 256)
  def _reduce_94(val, _values, result)
     result = Nodes::Switch.new(val[1], val[3], nil,
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 259)
  def _reduce_95(val, _values, result)
     result = Nodes::Switch.new(val[1], val[3], val[4],
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 262)
  def _reduce_96(val, _values, result)
     result = Nodes::Switch.new(val[1], [], val[3],
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 265)
  def _reduce_97(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 266)
  def _reduce_98(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 269)
  def _reduce_99(val, _values, result)
     result = Nodes::SwitchArm.new(val[0], val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 272)
  def _reduce_100(val, _values, result)
     result = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 275)
  def _reduce_101(val, _values, result)
     result = Nodes::Try.new(val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 279)
  def _reduce_102(val, _values, result)
     result = Nodes::FunDef.new(nil, val[3], val[5], nil,
        val[0].start, val[5].end)
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Taoism
