#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
module Taoism
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 286)

attr_reader :errors

def initialize(lexer)
  @lexer = lexer
  @errors = []
end

def parse
  do_parse
end

def next_token
  tok = @lexer.next_token
  return nil if tok.type == TokenType::EOF
  [tok.type, tok]
end

def on_error(error_id, val, stack)
  tok = Array(val).first
  msg = if tok.respond_to?(:lexeme)
    "unexpected token #{tok.lexeme.inspect} at #{tok.start.line}:#{tok.start.col}"
  else
    "parse error"
  end
  @errors << msg
end

private

def parse_int(tok)
  tok.lexeme.delete('_').to_i
end

def parse_float(tok)
  tok.lexeme.delete('_').to_f
end

def parse_string(tok)
  tok.lexeme[1...-1]
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    50,    28,    31,    30,    29,    32,    33,   118,    23,   106,
   173,   164,     3,    72,    72,    71,    71,    44,    24,    41,
    73,    73,    25,   166,   174,   148,    40,    51,    34,   104,
    45,   134,   105,    72,    41,    71,   149,   147,    42,    46,
    73,    62,    63,    68,   144,    48,    43,   146,    52,    28,
    31,    30,    29,    32,    33,   165,    23,    58,    59,    60,
    61,    49,    56,    53,    57,    54,    24,    64,    65,    66,
    25,    64,    65,    66,    40,    55,    34,    81,    58,    59,
    60,    61,    41,    56,    82,    57,    42,    13,    12,    11,
    16,    15,    62,    63,    43,    28,    31,    30,    29,    32,
    33,    83,    23,    64,    65,    66,    28,    31,    30,    29,
    32,    33,    24,    23,    62,    63,    25,    62,    63,    84,
    40,    85,    34,    24,    62,    63,    86,    25,    41,    62,
    63,    40,    42,    34,    62,    63,    52,    68,   102,    41,
    43,   119,   105,    42,   103,   106,   108,   110,    68,   113,
   114,    43,    28,    31,    30,    29,    32,    33,   113,    23,
   118,    55,   120,    28,    31,    30,    29,    32,    33,    24,
    23,   124,   130,    25,   131,   132,   133,    40,   136,    34,
    24,   155,   156,   157,    25,    41,   106,   159,    40,    42,
    34,   160,   106,   163,    68,   106,    41,    43,   169,   172,
    42,   175,   113,   179,   180,    68,   181,   182,    43,    28,
    31,    30,    29,    32,    33,   106,    23,   nil,   nil,   nil,
    28,    31,    30,    29,    32,    33,    24,    23,   nil,   nil,
    25,   nil,   nil,   nil,    40,    76,    34,    24,   nil,   nil,
   nil,    25,    41,   nil,   nil,    40,    42,    34,   nil,   nil,
   nil,    68,   nil,    41,    43,   nil,   nil,    42,   nil,   nil,
   nil,   nil,    68,   nil,   nil,    43,    28,    31,    30,    29,
    32,    33,   nil,    23,   nil,   nil,   nil,    28,    31,    30,
    29,    32,    33,    24,   nil,   nil,   nil,    25,   nil,   nil,
   nil,    40,   nil,    34,   nil,   nil,   nil,   nil,   nil,    41,
   nil,   nil,    40,    42,    34,   nil,   nil,   nil,    68,   nil,
    41,    43,   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,
   nil,   nil,    43,    28,    31,    30,    29,    32,    33,   nil,
    23,   nil,   nil,   nil,    28,    31,    30,    29,    32,    33,
    24,    23,   nil,   nil,    25,   nil,   nil,   nil,    40,   nil,
    34,    24,   nil,   nil,   nil,    25,    41,   nil,   nil,    40,
    42,    34,   nil,   nil,   nil,    68,   nil,    41,    43,   nil,
   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,
    28,    31,    30,    29,    32,    33,   nil,    23,   nil,   nil,
   nil,    28,    31,    30,    29,    32,    33,    24,    23,   nil,
   nil,    25,   nil,   nil,   nil,    40,   nil,    34,    24,   nil,
   nil,   nil,    25,    41,   nil,   nil,    40,    42,    34,   nil,
   nil,   nil,    68,   nil,    41,    43,   nil,   nil,    42,   nil,
   nil,   nil,   nil,    68,   nil,   nil,    43,    28,    31,    30,
    29,    32,    33,   nil,    23,   nil,   nil,   nil,    28,    31,
    30,    29,    32,    33,    24,    23,   nil,   nil,    25,   nil,
   nil,   nil,    40,   nil,    34,    24,   nil,   nil,   nil,    25,
    41,   nil,   nil,    40,    42,    34,   nil,   nil,   nil,    68,
   nil,    41,    43,   nil,   nil,    42,   nil,   nil,   nil,   nil,
    68,   nil,   nil,    43,    28,    31,    30,    29,    32,    33,
   nil,    23,   nil,   nil,   nil,    28,    31,    30,    29,    32,
    33,    24,    23,   nil,   nil,    25,   nil,   nil,   nil,    40,
   nil,    34,    24,   nil,   nil,   nil,    25,    41,   nil,   nil,
    40,    42,    34,   nil,   nil,   nil,    68,   nil,    41,    43,
   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,
    43,    28,    31,    30,    29,    32,    33,   nil,    23,   nil,
   nil,   nil,    28,    31,    30,    29,    32,    33,    24,    23,
   nil,   nil,    25,   nil,   nil,   nil,    40,   nil,    34,    24,
   nil,   nil,   nil,    25,    41,   nil,   nil,    40,    42,    34,
   nil,   nil,   nil,    68,   nil,    41,    43,   nil,   nil,    42,
   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,    28,    31,
    30,    29,    32,    33,   nil,    23,   nil,   nil,   nil,    28,
    31,    30,    29,    32,    33,    24,    23,   nil,   nil,    25,
   nil,   nil,   nil,    40,   nil,    34,    24,   nil,   nil,   nil,
    25,    41,   nil,   nil,    40,    42,    34,   nil,   nil,   nil,
    68,   nil,    41,    43,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    68,   nil,   nil,    43,    28,    31,    30,    29,    32,
    33,   nil,    23,   nil,   nil,   nil,    28,    31,    30,    29,
    32,    33,    24,    23,   nil,   nil,    25,   nil,   nil,   nil,
    40,   nil,    34,    24,   nil,   nil,   nil,    25,    41,   nil,
   nil,    40,    42,    34,   nil,   nil,   nil,    68,   nil,    41,
    43,   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,
   nil,    43,    28,    31,    30,    29,    32,    33,   nil,    23,
   nil,   nil,   nil,    28,    31,    30,    29,    32,    33,    24,
    23,   nil,   nil,    25,   nil,   nil,   nil,    40,   nil,    34,
    24,   nil,   nil,   nil,    25,    41,   nil,   nil,    40,    42,
    34,   nil,   nil,   nil,    68,   nil,    41,    43,   nil,   nil,
    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,    28,
    31,    30,    29,    32,    33,   nil,    23,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
    25,   nil,   nil,   nil,    40,   nil,    34,   nil,   nil,   nil,
   nil,   nil,    41,   nil,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    68,   nil,   nil,    43,    28,    31,    30,    29,    32,
    33,   nil,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    24,   nil,   nil,   nil,    25,   nil,   nil,   nil,
    40,   nil,    34,   nil,   nil,   nil,   nil,   nil,    41,   129,
   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,
    43,    28,    31,    30,    29,    32,    33,   nil,    23,   nil,
   nil,   nil,    28,    31,    30,    29,    32,    33,    24,    23,
   nil,   nil,    25,   nil,   nil,   152,    40,   nil,    34,    24,
   nil,   nil,   nil,    25,    41,   129,   nil,    40,    42,    34,
   nil,   nil,   nil,    68,   nil,    41,    43,   nil,   nil,    42,
   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,    28,    31,
    30,    29,    32,    33,   nil,    23,   nil,   nil,   nil,    28,
    31,    30,    29,    32,    33,    24,    23,   nil,   nil,    25,
   nil,   nil,   nil,    40,   nil,    34,    24,   nil,   nil,   nil,
    25,    41,   nil,   nil,    40,    42,    34,   nil,   nil,   nil,
    68,   nil,    41,    43,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    68,   nil,   nil,    43,    28,    31,    30,    29,    32,
    33,   nil,    23,   nil,   nil,   nil,    28,    31,    30,    29,
    32,    33,    24,    23,   nil,   nil,    25,   nil,   nil,   nil,
    40,   nil,    34,    24,   nil,   nil,   nil,    25,    41,   nil,
   nil,    40,    42,    34,   nil,   nil,   nil,    68,   nil,    41,
    43,   nil,   nil,    42,   nil,   nil,   nil,   nil,    68,   nil,
   nil,    43,    28,    31,    30,    29,    32,    33,   nil,    23,
   nil,   nil,   nil,    28,    31,    30,    29,    32,    33,    24,
    23,   nil,   nil,    25,   nil,   nil,   nil,    40,   nil,    34,
    24,   nil,   nil,   nil,    25,    41,   nil,   nil,    40,    42,
    34,   nil,   nil,   nil,    68,   nil,    41,    43,   nil,   nil,
    42,   nil,   nil,   nil,   nil,    68,   nil,   nil,    43,    28,
    31,    30,    29,    32,    33,   nil,    23,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
    25,   nil,   nil,   nil,    40,   nil,    34,   nil,   nil,   nil,
   nil,   nil,    41,   nil,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    68,   nil,   nil,    43 ]

racc_action_check = [
    15,   122,   122,   122,   122,   122,   122,   116,   122,   124,
   164,   144,     1,    26,    80,    26,    80,     3,   122,   124,
    26,    80,   122,   145,   164,   122,   122,    15,   122,    75,
     4,   116,    75,   145,   122,   145,   122,   122,   122,    11,
   145,    20,    20,   122,   122,    12,   122,   122,    15,     2,
     2,     2,     2,     2,     2,   144,     2,    19,    19,    19,
    19,    13,    19,    16,    19,    17,     2,    21,    21,    21,
     2,    95,    95,    95,     2,    18,     2,    46,    88,    88,
    88,    88,     2,    88,    47,    88,     2,     2,     2,     2,
     2,     2,    89,    89,     2,    23,    23,    23,    23,    23,
    23,    50,    23,    96,    96,    96,    24,    24,    24,    24,
    24,    24,    23,    24,    90,    90,    23,    91,    91,    51,
    23,    52,    23,    24,    92,    92,    53,    24,    23,    93,
    93,    24,    23,    24,    94,    94,    68,    23,    73,    24,
    23,   100,   100,    24,    74,    78,    79,    82,    24,    83,
    84,    24,    25,    25,    25,    25,    25,    25,    85,    25,
    86,    87,   101,    34,    34,    34,    34,    34,    34,    25,
    34,   107,   111,    25,   112,   114,   115,    25,   118,    25,
    34,   126,   128,   129,    34,    25,   130,   131,    34,    25,
    34,   132,   133,   137,    25,   149,    34,    25,   153,   160,
    34,   165,   172,   174,   175,    34,   177,   179,    34,    40,
    40,    40,    40,    40,    40,   181,    40,   nil,   nil,   nil,
    41,    41,    41,    41,    41,    41,    40,    41,   nil,   nil,
    40,   nil,   nil,   nil,    40,    40,    40,    41,   nil,   nil,
   nil,    41,    40,   nil,   nil,    41,    40,    41,   nil,   nil,
   nil,    40,   nil,    41,    40,   nil,   nil,    41,   nil,   nil,
   nil,   nil,    41,   nil,   nil,    41,    42,    42,    42,    42,
    42,    42,   nil,    42,   nil,   nil,   nil,    43,    43,    43,
    43,    43,    43,    42,   nil,   nil,   nil,    42,   nil,   nil,
   nil,    42,   nil,    42,   nil,   nil,   nil,   nil,   nil,    42,
   nil,   nil,    43,    42,    43,   nil,   nil,   nil,    42,   nil,
    43,    42,   nil,   nil,    43,   nil,   nil,   nil,   nil,    43,
   nil,   nil,    43,    54,    54,    54,    54,    54,    54,   nil,
    54,   nil,   nil,   nil,    55,    55,    55,    55,    55,    55,
    54,    55,   nil,   nil,    54,   nil,   nil,   nil,    54,   nil,
    54,    55,   nil,   nil,   nil,    55,    54,   nil,   nil,    55,
    54,    55,   nil,   nil,   nil,    54,   nil,    55,    54,   nil,
   nil,    55,   nil,   nil,   nil,   nil,    55,   nil,   nil,    55,
    56,    56,    56,    56,    56,    56,   nil,    56,   nil,   nil,
   nil,    57,    57,    57,    57,    57,    57,    56,    57,   nil,
   nil,    56,   nil,   nil,   nil,    56,   nil,    56,    57,   nil,
   nil,   nil,    57,    56,   nil,   nil,    57,    56,    57,   nil,
   nil,   nil,    56,   nil,    57,    56,   nil,   nil,    57,   nil,
   nil,   nil,   nil,    57,   nil,   nil,    57,    58,    58,    58,
    58,    58,    58,   nil,    58,   nil,   nil,   nil,    59,    59,
    59,    59,    59,    59,    58,    59,   nil,   nil,    58,   nil,
   nil,   nil,    58,   nil,    58,    59,   nil,   nil,   nil,    59,
    58,   nil,   nil,    59,    58,    59,   nil,   nil,   nil,    58,
   nil,    59,    58,   nil,   nil,    59,   nil,   nil,   nil,   nil,
    59,   nil,   nil,    59,    60,    60,    60,    60,    60,    60,
   nil,    60,   nil,   nil,   nil,    61,    61,    61,    61,    61,
    61,    60,    61,   nil,   nil,    60,   nil,   nil,   nil,    60,
   nil,    60,    61,   nil,   nil,   nil,    61,    60,   nil,   nil,
    61,    60,    61,   nil,   nil,   nil,    60,   nil,    61,    60,
   nil,   nil,    61,   nil,   nil,   nil,   nil,    61,   nil,   nil,
    61,    62,    62,    62,    62,    62,    62,   nil,    62,   nil,
   nil,   nil,    63,    63,    63,    63,    63,    63,    62,    63,
   nil,   nil,    62,   nil,   nil,   nil,    62,   nil,    62,    63,
   nil,   nil,   nil,    63,    62,   nil,   nil,    63,    62,    63,
   nil,   nil,   nil,    62,   nil,    63,    62,   nil,   nil,    63,
   nil,   nil,   nil,   nil,    63,   nil,   nil,    63,    64,    64,
    64,    64,    64,    64,   nil,    64,   nil,   nil,   nil,    65,
    65,    65,    65,    65,    65,    64,    65,   nil,   nil,    64,
   nil,   nil,   nil,    64,   nil,    64,    65,   nil,   nil,   nil,
    65,    64,   nil,   nil,    65,    64,    65,   nil,   nil,   nil,
    64,   nil,    65,    64,   nil,   nil,    65,   nil,   nil,   nil,
   nil,    65,   nil,   nil,    65,    66,    66,    66,    66,    66,
    66,   nil,    66,   nil,   nil,   nil,    71,    71,    71,    71,
    71,    71,    66,    71,   nil,   nil,    66,   nil,   nil,   nil,
    66,   nil,    66,    71,   nil,   nil,   nil,    71,    66,   nil,
   nil,    71,    66,    71,   nil,   nil,   nil,    66,   nil,    71,
    66,   nil,   nil,    71,   nil,   nil,   nil,   nil,    71,   nil,
   nil,    71,    72,    72,    72,    72,    72,    72,   nil,    72,
   nil,   nil,   nil,    81,    81,    81,    81,    81,    81,    72,
    81,   nil,   nil,    72,   nil,   nil,   nil,    72,   nil,    72,
    81,   nil,   nil,   nil,    81,    72,   nil,   nil,    81,    72,
    81,   nil,   nil,   nil,    72,   nil,    81,    72,   nil,   nil,
    81,   nil,   nil,   nil,   nil,    81,   nil,   nil,    81,   105,
   105,   105,   105,   105,   105,   nil,   105,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   105,   nil,   nil,   nil,
   105,   nil,   nil,   nil,   105,   nil,   105,   nil,   nil,   nil,
   nil,   nil,   105,   nil,   nil,   nil,   105,   nil,   nil,   nil,
   nil,   105,   nil,   nil,   105,   108,   108,   108,   108,   108,
   108,   nil,   108,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   108,   nil,   nil,   nil,   108,   nil,   nil,   nil,
   108,   nil,   108,   nil,   nil,   nil,   nil,   nil,   108,   108,
   nil,   nil,   108,   nil,   nil,   nil,   nil,   108,   nil,   nil,
   108,   125,   125,   125,   125,   125,   125,   nil,   125,   nil,
   nil,   nil,   136,   136,   136,   136,   136,   136,   125,   136,
   nil,   nil,   125,   nil,   nil,   125,   125,   nil,   125,   136,
   nil,   nil,   nil,   136,   125,   125,   nil,   136,   125,   136,
   nil,   nil,   nil,   125,   nil,   136,   125,   nil,   nil,   136,
   nil,   nil,   nil,   nil,   136,   nil,   nil,   136,   146,   146,
   146,   146,   146,   146,   nil,   146,   nil,   nil,   nil,   156,
   156,   156,   156,   156,   156,   146,   156,   nil,   nil,   146,
   nil,   nil,   nil,   146,   nil,   146,   156,   nil,   nil,   nil,
   156,   146,   nil,   nil,   156,   146,   156,   nil,   nil,   nil,
   146,   nil,   156,   146,   nil,   nil,   156,   nil,   nil,   nil,
   nil,   156,   nil,   nil,   156,   157,   157,   157,   157,   157,
   157,   nil,   157,   nil,   nil,   nil,   166,   166,   166,   166,
   166,   166,   157,   166,   nil,   nil,   157,   nil,   nil,   nil,
   157,   nil,   157,   166,   nil,   nil,   nil,   166,   157,   nil,
   nil,   166,   157,   166,   nil,   nil,   nil,   157,   nil,   166,
   157,   nil,   nil,   166,   nil,   nil,   nil,   nil,   166,   nil,
   nil,   166,   173,   173,   173,   173,   173,   173,   nil,   173,
   nil,   nil,   nil,   180,   180,   180,   180,   180,   180,   173,
   180,   nil,   nil,   173,   nil,   nil,   nil,   173,   nil,   173,
   180,   nil,   nil,   nil,   180,   173,   nil,   nil,   180,   173,
   180,   nil,   nil,   nil,   173,   nil,   180,   173,   nil,   nil,
   180,   nil,   nil,   nil,   nil,   180,   nil,   nil,   180,   182,
   182,   182,   182,   182,   182,   nil,   182,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   182,   nil,   nil,   nil,
   182,   nil,   nil,   nil,   182,   nil,   182,   nil,   nil,   nil,
   nil,   nil,   182,   nil,   nil,   nil,   182,   nil,   nil,   nil,
   nil,   182,   nil,   nil,   182 ]

racc_action_pointer = [
   nil,    12,    46,    17,    -4,   nil,   nil,   nil,   nil,   nil,
   nil,    36,    42,    58,   nil,    -3,    60,    42,    53,    43,
    32,    56,   nil,    92,   103,   149,   -15,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   160,   nil,   nil,   nil,   nil,   nil,
   206,   217,   263,   274,   nil,   nil,    59,    49,   nil,   nil,
    71,   116,    91,   100,   320,   331,   377,   388,   434,   445,
   491,   502,   548,   559,   605,   616,   662,   nil,    85,   nil,
   nil,   673,   719,   135,   113,     0,   nil,   nil,   119,   120,
   -14,   730,   144,   146,   147,   155,   157,   139,    64,    83,
   105,   108,   115,   120,   125,    60,    92,   nil,   nil,   nil,
   110,   133,   nil,   nil,   nil,   776,   nil,   134,   822,   nil,
   nil,   141,   142,   nil,   144,   145,     4,   nil,   160,   nil,
   nil,   nil,    -2,   nil,   -17,   868,   154,   nil,   132,   133,
   160,   184,   188,   166,   nil,   nil,   879,   159,   nil,   nil,
   nil,   nil,   nil,   nil,     8,     5,   925,   nil,   nil,   169,
   nil,   nil,   nil,   171,   nil,   nil,   936,   982,   nil,   nil,
   169,   nil,   nil,   nil,    -8,   198,   993,   nil,   nil,   nil,
   nil,   nil,   199,  1039,   200,   186,   nil,   175,   nil,   189,
  1050,   189,  1096,   nil,   nil,   nil ]

racc_action_default = [
    -2,  -101,    -1,  -101,    -3,    -5,    -6,    -7,    -8,    -9,
   -10,  -101,  -101,  -101,   -31,  -101,  -101,   -44,   -45,   -47,
   -49,   -56,   -59,  -101,  -101,  -101,   -66,   -67,   -68,   -72,
   -73,   -74,   -75,   -76,  -101,   -78,   -79,   -80,   -81,   -82,
  -101,  -101,  -101,  -101,   186,    -4,  -101,   -25,   -27,   -26,
  -101,  -101,  -101,  -101,  -101,  -101,  -101,  -101,  -101,  -101,
  -101,  -101,  -101,  -101,  -101,  -101,  -101,   -63,  -101,   -64,
   -65,  -101,  -101,  -101,  -101,  -101,   -84,   -85,  -101,  -101,
   -99,  -101,  -101,   -34,  -101,   -34,  -101,   -46,   -48,   -50,
   -51,   -52,   -53,   -54,   -55,   -57,   -58,   -60,   -61,   -62,
  -101,  -101,   -71,   -77,   -83,  -101,   -11,   -90,  -101,   -24,
   -28,  -101,   -35,   -36,  -101,  -101,  -101,   -39,   -41,   -69,
   -70,   -86,  -101,   -87,  -101,  -101,  -101,   -95,  -101,  -101,
  -101,  -101,  -101,  -101,   -38,   -40,  -101,   -12,   -14,   -15,
   -16,   -17,   -18,   -19,  -101,   -66,  -101,   -30,   -43,  -101,
   -88,   -89,   -92,  -101,   -96,   -94,  -101,  -101,   -32,   -37,
  -101,  -100,   -42,   -13,  -101,  -101,  -101,   -29,   -91,   -93,
   -97,   -98,   -34,  -101,  -101,  -101,   -23,  -101,   -20,  -101,
  -101,  -101,  -101,   -21,   -33,   -22 ]

racc_goto_table = [
    74,    10,   107,   111,    80,   115,    77,    78,    79,    67,
    69,    70,    75,   126,   117,   127,    89,    90,    91,    92,
    93,    94,    95,    96,     1,     2,     4,     5,     6,     7,
   153,     8,   154,     9,   122,   137,   138,    77,   101,   139,
   140,   141,   142,   100,   135,    47,   116,   109,   150,    87,
    97,    98,    99,    88,   158,   151,   123,   161,   125,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   121,   nil,   168,   128,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   145,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   128,   177,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   162,   nil,   nil,   184,   nil,   nil,   nil,   nil,
   nil,   nil,   167,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   143,   170,   171,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   176,   nil,   nil,   nil,   nil,   nil,   nil,   178,
   nil,   nil,   nil,   nil,   nil,   nil,   183,   nil,   185 ]

racc_goto_check = [
    17,     9,    21,    20,    18,    20,    17,    17,    17,    30,
    30,    30,    32,    40,    24,    41,    28,    28,    28,    28,
    28,    28,    29,    29,     1,     2,     3,     4,     5,     6,
    40,     7,    41,     8,    10,    11,    12,    17,    17,    13,
    14,    15,    16,    32,    24,    19,    23,    17,    21,    26,
    30,    30,    30,    27,    21,    34,    38,    21,    39,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    17,   nil,    21,    17,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    17,    20,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    17,   nil,   nil,    21,   nil,   nil,   nil,   nil,
   nil,   nil,    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     9,    17,    17,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    17,   nil,   nil,   nil,   nil,   nil,   nil,    17,
   nil,   nil,   nil,   nil,   nil,   nil,    17,   nil,    17 ]

racc_goto_pointer = [
   nil,    24,    25,    24,    25,    26,    27,    29,    31,    -1,
   -72,   -87,   -86,   -83,   -82,   -81,   -80,   -34,   -39,    33,
   -80,   -76,   nil,   -40,   -72,   nil,    -5,    -2,   -40,   -40,
   -14,   nil,   -28,   nil,   -69,   nil,   nil,   nil,   -51,   -50,
   -95,   -93 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,    26,   nil,
   nil,   nil,   112,   nil,   nil,    17,    18,    19,    20,    21,
    22,    27,   nil,    35,    36,    37,    38,    39,   nil,   nil,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 55, :_reduce_1,
  0, 56, :_reduce_2,
  2, 56, :_reduce_3,
  3, 56, :_reduce_4,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  0, 64, :_reduce_11,
  2, 64, :_reduce_12,
  3, 64, :_reduce_13,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  4, 66, :_reduce_20,
  5, 66, :_reduce_21,
  6, 66, :_reduce_22,
  3, 67, :_reduce_23,
  4, 58, :_reduce_24,
  2, 61, :_reduce_25,
  2, 62, :_reduce_26,
  1, 73, :_reduce_27,
  3, 73, :_reduce_28,
  2, 68, :_reduce_29,
  1, 69, :_reduce_30,
  1, 63, :_reduce_31,
  6, 59, :_reduce_32,
  10, 59, :_reduce_33,
  0, 74, :_reduce_34,
  1, 74, :_reduce_35,
  1, 76, :_reduce_36,
  3, 76, :_reduce_37,
  5, 60, :_reduce_38,
  1, 77, :_reduce_39,
  2, 77, :_reduce_40,
  1, 78, :_reduce_41,
  3, 78, :_reduce_42,
  3, 75, :_reduce_43,
  1, 71, :_reduce_44,
  1, 79, :_reduce_none,
  3, 79, :_reduce_46,
  1, 80, :_reduce_none,
  3, 80, :_reduce_48,
  1, 81, :_reduce_none,
  3, 81, :_reduce_50,
  3, 81, :_reduce_51,
  3, 81, :_reduce_52,
  3, 81, :_reduce_53,
  3, 81, :_reduce_54,
  3, 81, :_reduce_55,
  1, 82, :_reduce_none,
  3, 82, :_reduce_57,
  3, 82, :_reduce_58,
  1, 83, :_reduce_none,
  3, 83, :_reduce_60,
  3, 83, :_reduce_61,
  3, 83, :_reduce_62,
  2, 84, :_reduce_63,
  2, 84, :_reduce_64,
  2, 84, :_reduce_65,
  1, 84, :_reduce_none,
  1, 72, :_reduce_none,
  1, 72, :_reduce_68,
  4, 72, :_reduce_69,
  4, 72, :_reduce_70,
  3, 72, :_reduce_71,
  1, 85, :_reduce_72,
  1, 85, :_reduce_73,
  1, 85, :_reduce_74,
  1, 85, :_reduce_75,
  1, 85, :_reduce_76,
  3, 85, :_reduce_77,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  3, 87, :_reduce_83,
  2, 87, :_reduce_84,
  1, 86, :_reduce_85,
  3, 86, :_reduce_86,
  4, 88, :_reduce_87,
  2, 92, :_reduce_88,
  2, 92, :_reduce_89,
  0, 92, :_reduce_90,
  2, 70, :_reduce_91,
  5, 89, :_reduce_92,
  6, 89, :_reduce_93,
  5, 89, :_reduce_94,
  1, 93, :_reduce_95,
  2, 93, :_reduce_96,
  3, 95, :_reduce_97,
  3, 94, :_reduce_98,
  2, 90, :_reduce_99,
  6, 91, :_reduce_100 ]

racc_reduce_n = 101

racc_shift_n = 186

racc_token_table = {
  false => 0,
  :error => 1,
  :ILLEGAL => 2,
  :IDENTIFIER => 3,
  :STRING => 4,
  :FLOAT => 5,
  :INT => 6,
  :BOOL => 7,
  :NONE => 8,
  :PLUS => 9,
  :MINUS => 10,
  :STAR => 11,
  :SLASH => 12,
  :MODULO => 13,
  :GREATER => 14,
  :GREATEREQ => 15,
  :LESS => 16,
  :LESSEQ => 17,
  :EQUAL => 18,
  :EQUALEQ => 19,
  :BANG => 20,
  :BANGEQ => 21,
  :AND => 22,
  :OR => 23,
  :NOT => 24,
  :PIPE => 25,
  :LBRACE => 26,
  :RBRACE => 27,
  :LSQUARE => 28,
  :RSQUARE => 29,
  :LPAREN => 30,
  :RPAREN => 31,
  :COMMA => 32,
  :COLON => 33,
  :SEMI => 34,
  :DOT => 35,
  :IF => 36,
  :ELSE => 37,
  :LOOP => 38,
  :LEAVE => 39,
  :SWITCH => 40,
  :PACKAGE => 41,
  :IMPORT => 42,
  :CONST => 43,
  :DATA => 44,
  :FUN => 45,
  :LET => 46,
  :MUT => 47,
  :TRY => 48,
  :RETURN => 49,
  :EQARROW => 50,
  :ARROW => 51,
  :EOF => 52,
  :UMINUS => 53 }

racc_nt_base = 54

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "ILLEGAL",
  "IDENTIFIER",
  "STRING",
  "FLOAT",
  "INT",
  "BOOL",
  "NONE",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "MODULO",
  "GREATER",
  "GREATEREQ",
  "LESS",
  "LESSEQ",
  "EQUAL",
  "EQUALEQ",
  "BANG",
  "BANGEQ",
  "AND",
  "OR",
  "NOT",
  "PIPE",
  "LBRACE",
  "RBRACE",
  "LSQUARE",
  "RSQUARE",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "COLON",
  "SEMI",
  "DOT",
  "IF",
  "ELSE",
  "LOOP",
  "LEAVE",
  "SWITCH",
  "PACKAGE",
  "IMPORT",
  "CONST",
  "DATA",
  "FUN",
  "LET",
  "MUT",
  "TRY",
  "RETURN",
  "EQARROW",
  "ARROW",
  "EOF",
  "UMINUS",
  "$start",
  "program",
  "top_stmts",
  "top_stmt",
  "const_stmt",
  "fun_def",
  "data_def",
  "import_stmt",
  "package_stmt",
  "expr_stmt",
  "block_stmts",
  "block_stmt",
  "let_stmt",
  "assign_stmt",
  "return_stmt",
  "leave_stmt",
  "loop_stmt",
  "expr",
  "postfix_expr",
  "path",
  "params",
  "block",
  "param_list",
  "field_list",
  "field",
  "or_expr",
  "and_expr",
  "cmp_expr",
  "add_expr",
  "mul_expr",
  "unary_expr",
  "primary",
  "args",
  "list_lit",
  "if_expr",
  "switch_expr",
  "try_expr",
  "fun_lit",
  "else_clause",
  "switch_body",
  "else_arm",
  "switch_arm" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_1(val, _values, result)
          first = val[0].first
      last  = val[0].last
      result = Nodes::Program.new(val[0],
        first ? first.start : nil,
        last  ? last.end   : nil)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_2(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_3(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_4(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_11(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_12(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_13(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_20(val, _values, result)
     result = Nodes::Let.new(val[1].lexeme, val[3], false,
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_21(val, _values, result)
     result = Nodes::Let.new(val[2].lexeme, val[4], true,
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_22(val, _values, result)
     result = Nodes::LetPair.new(val[1].lexeme, val[3].lexeme, val[5],
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_23(val, _values, result)
     result = Nodes::Assign.new(val[0], val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_24(val, _values, result)
     result = Nodes::Const.new(val[1].lexeme, val[3],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_25(val, _values, result)
     result = Nodes::Import.new(val[1],
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_26(val, _values, result)
     result = Nodes::Package.new(val[1].lexeme,
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 88)
  def _reduce_27(val, _values, result)
     result = val[0].lexeme
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_28(val, _values, result)
     result = val[0] + '.' + val[2].lexeme
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 92)
  def _reduce_29(val, _values, result)
     result = Nodes::Return.new(val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_30(val, _values, result)
     result = Nodes::Leave.new(val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_31(val, _values, result)
     result = Nodes::ExprStmt.new(val[0],
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 103)
  def _reduce_32(val, _values, result)
     result = Nodes::FunDef.new(val[1].lexeme, val[3], val[5], nil,
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 107)
  def _reduce_33(val, _values, result)
     result = Nodes::FunDef.new(val[5].lexeme, val[8], val[9],
        Nodes::Receiver.new(val[2].lexeme, val[3].lexeme,
          val[1].start, val[4].end),
        val[0].start, val[9].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 112)
  def _reduce_34(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 113)
  def _reduce_35(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_36(val, _values, result)
     result = [val[0].lexeme]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_37(val, _values, result)
     val[0] << val[2].lexeme; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 119)
  def _reduce_38(val, _values, result)
     result = Nodes::DataDef.new(val[1].lexeme, val[3],
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 122)
  def _reduce_39(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_40(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 126)
  def _reduce_41(val, _values, result)
     result = Nodes::Field.new(val[0].lexeme, nil,
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 129)
  def _reduce_42(val, _values, result)
     result = Nodes::Field.new(val[0].lexeme, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 133)
  def _reduce_43(val, _values, result)
     result = Nodes::Block.new(val[1],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 136)
  def _reduce_44(val, _values, result)
     result = val[0]
    result
  end
.,.,

# reduce 45 omitted

module_eval(<<'.,.,', 'parser.y', 140)
  def _reduce_46(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :or, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 47 omitted

module_eval(<<'.,.,', 'parser.y', 145)
  def _reduce_48(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :and, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 49 omitted

module_eval(<<'.,.,', 'parser.y', 150)
  def _reduce_50(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'==', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 153)
  def _reduce_51(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'!=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 156)
  def _reduce_52(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'>', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 159)
  def _reduce_53(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'>=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 162)
  def _reduce_54(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'<', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 165)
  def _reduce_55(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'<=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 56 omitted

module_eval(<<'.,.,', 'parser.y', 170)
  def _reduce_57(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'+', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 173)
  def _reduce_58(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'-', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 59 omitted

module_eval(<<'.,.,', 'parser.y', 178)
  def _reduce_60(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'*', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 181)
  def _reduce_61(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'/', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 184)
  def _reduce_62(val, _values, result)
     result = Nodes::BinaryOp.new(val[0], :'%', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 188)
  def _reduce_63(val, _values, result)
     result = Nodes::UnaryOp.new(:'-', val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 191)
  def _reduce_64(val, _values, result)
     result = Nodes::UnaryOp.new(:'!', val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 194)
  def _reduce_65(val, _values, result)
     result = Nodes::UnaryOp.new(:'!', val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

# reduce 66 omitted

# reduce 67 omitted

module_eval(<<'.,.,', 'parser.y', 200)
  def _reduce_68(val, _values, result)
     result = Nodes::Identifier.new(val[0].lexeme,
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 203)
  def _reduce_69(val, _values, result)
     result = Nodes::Call.new(val[0], val[2],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 206)
  def _reduce_70(val, _values, result)
     result = Nodes::Index.new(val[0], val[2],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 209)
  def _reduce_71(val, _values, result)
     result = Nodes::DotExpr.new(val[0], val[2].lexeme,
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 213)
  def _reduce_72(val, _values, result)
     result = Nodes::IntLit.new(parse_int(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 216)
  def _reduce_73(val, _values, result)
     result = Nodes::FloatLit.new(parse_float(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 219)
  def _reduce_74(val, _values, result)
     result = Nodes::StringLit.new(parse_string(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 222)
  def _reduce_75(val, _values, result)
     result = Nodes::BoolLit.new(val[0].lexeme == 'True',
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 225)
  def _reduce_76(val, _values, result)
     result = Nodes::NoneLit.new(val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 227)
  def _reduce_77(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

module_eval(<<'.,.,', 'parser.y', 235)
  def _reduce_83(val, _values, result)
     result = Nodes::ListLit.new(val[1],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 238)
  def _reduce_84(val, _values, result)
     result = Nodes::ListLit.new([],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 241)
  def _reduce_85(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 242)
  def _reduce_86(val, _values, result)
     val[0] << val[2]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 245)
  def _reduce_87(val, _values, result)
     result = Nodes::If.new(val[1], val[2], val[3],
        val[0].start, val[3] ? val[3].end : val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 248)
  def _reduce_88(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 249)
  def _reduce_89(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 250)
  def _reduce_90(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 253)
  def _reduce_91(val, _values, result)
     result = Nodes::Loop.new(val[1], val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 256)
  def _reduce_92(val, _values, result)
     result = Nodes::Switch.new(val[1], val[3], nil,
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 259)
  def _reduce_93(val, _values, result)
     result = Nodes::Switch.new(val[1], val[3], val[4],
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 262)
  def _reduce_94(val, _values, result)
     result = Nodes::Switch.new(val[1], [], val[3],
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 265)
  def _reduce_95(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 266)
  def _reduce_96(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 269)
  def _reduce_97(val, _values, result)
     result = Nodes::SwitchArm.new(val[0], val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 272)
  def _reduce_98(val, _values, result)
     result = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 275)
  def _reduce_99(val, _values, result)
     result = Nodes::Try.new(val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 279)
  def _reduce_100(val, _values, result)
     result = Nodes::FunDef.new(nil, val[3], val[5], nil,
        val[0].start, val[5].end)
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Taoism
