#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
module Taoism
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 273)

def initialize(lexer)
  @lexer = lexer
  @errors = []
end

def parse
  do_parse
end

def next_token
  tok = @lexer.next_token
  return nil if tok.type == TokenType::EOF
  [tok.type, tok]
end

def on_error(error_id, val, stack)
  tok = val[0] || stack.last
  msg = "unexpected token #{tok.lexeme.inspect} at #{tok.start.line}:#{tok.start.col}"
  @errors << msg
end

private

def identifier_or_none(tok)
  if tok.lexeme == 'None'
    AST::NoneLit.new(tok.start, tok.end)
  else
    AST::Identifier.new(tok.lexeme, tok.start, tok.end)
  end
end

def parse_int(tok)
  tok.lexeme.delete('_').to_i
end

def parse_float(tok)
  tok.lexeme.delete('_').to_f
end

def parse_string(tok)
  tok.lexeme[1...-1]
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    65,    18,    39,    38,    37,    40,    53,    33,    96,    92,
     3,    73,    74,    75,    76,    52,    71,    34,    72,    48,
   125,    58,    97,   126,    60,    47,    66,    41,    18,    39,
    38,    37,    40,    48,    33,    49,    23,    50,    21,    20,
    19,    26,    25,    16,    34,    51,    22,    67,    61,    54,
    68,   148,    47,    69,    41,    18,    39,    38,    37,    40,
    48,    33,    49,    23,    50,    21,    20,    19,    26,    25,
    16,    34,    51,    22,    18,    39,    38,    37,    40,    47,
    33,    41,    85,    70,    84,   143,    57,    48,    91,    86,
    34,    50,    92,    56,    77,    78,    64,    98,    47,    51,
    41,    18,    39,    38,    37,    40,    48,    33,   160,    85,
    50,    84,    79,    80,    81,    64,    86,    34,    51,   100,
    18,    39,    38,    37,    40,    47,    33,    41,    79,    80,
    81,    77,    78,    48,    77,    78,    34,    50,    79,    80,
    81,   102,    64,   103,    47,    51,    41,    18,    39,    38,
    37,    40,    48,    33,    77,    78,    50,    77,    78,    77,
    78,    64,    67,    34,    51,    77,    78,   144,   126,   104,
   105,    47,    89,    41,    18,    39,    38,    37,    40,    48,
    33,   106,    55,    50,   107,   123,   124,   129,    64,   131,
    34,    51,    57,    18,    39,    38,    37,    40,    47,    56,
    41,   132,    73,    74,    75,    76,    48,    71,   133,    72,
    50,   135,   138,   139,   138,    64,   143,    47,    51,    41,
    18,    39,    38,    37,    40,    48,    33,    70,   145,    50,
   147,   154,   156,   157,    64,   158,    34,    51,   159,    18,
    39,    38,    37,    40,    47,    33,    41,   162,    92,   167,
   168,   169,    48,    92,   172,    34,    50,   173,    92,   177,
   178,    64,   181,    47,    51,    41,    18,    39,    38,    37,
    40,    48,    33,   138,   185,    50,    92,   nil,   nil,   nil,
    64,   nil,    34,    51,   nil,    18,    39,    38,    37,    40,
    47,    33,    41,   nil,   nil,   nil,   nil,   nil,    48,   nil,
   nil,    34,    50,   nil,   nil,   nil,   nil,    64,   nil,    47,
    51,    41,    18,    39,    38,    37,    40,    48,    33,   nil,
   nil,    50,   nil,   nil,   nil,   nil,    64,   nil,    34,    51,
   nil,    18,    39,    38,    37,    40,    47,    33,    41,   nil,
   nil,   nil,   nil,   nil,    48,   nil,   nil,    34,    50,   nil,
   nil,   nil,   nil,    64,   nil,    47,    51,    41,    18,    39,
    38,    37,    40,    48,    33,   nil,   nil,    50,   nil,   nil,
   nil,   nil,    64,   nil,    34,    51,   nil,    18,    39,    38,
    37,    40,    47,    33,    41,   nil,   nil,   nil,   nil,   nil,
    48,   nil,   nil,    34,    50,   nil,   nil,   nil,   nil,    64,
   nil,    47,    51,    41,    18,    39,    38,    37,    40,    48,
    33,   nil,   nil,    50,   nil,   nil,   nil,   nil,    64,   nil,
    34,    51,   nil,    18,    39,    38,    37,    40,    47,    33,
    41,   nil,   nil,   nil,   nil,   nil,    48,   nil,   nil,    34,
    50,   nil,   nil,   nil,   nil,    64,   nil,    47,    51,    41,
    18,    39,    38,    37,    40,    48,    33,   nil,   nil,    50,
   nil,   nil,   nil,   nil,    64,   nil,    34,    51,   nil,    18,
    39,    38,    37,    40,    47,    33,    41,   nil,   nil,   nil,
   nil,   nil,    48,   nil,   nil,    34,    50,   nil,   nil,   nil,
   nil,    64,   nil,    47,    51,    41,    18,    39,    38,    37,
    40,    48,    33,   nil,   nil,    50,   nil,   nil,   nil,   nil,
    64,   nil,    34,    51,   nil,    18,    39,    38,    37,    40,
    47,    33,    41,   nil,   nil,   nil,   nil,   nil,    48,   nil,
   nil,    34,    50,   nil,   nil,   nil,   nil,    64,   nil,    47,
    51,    41,    18,    39,    38,    37,    40,    48,    33,   nil,
   nil,    50,   nil,   nil,   nil,   nil,    64,   nil,    34,    51,
   nil,    18,    39,    38,    37,    40,    47,    33,    41,   nil,
   nil,   nil,   nil,   nil,    48,   nil,   nil,    34,    50,   nil,
   nil,   nil,   nil,    64,   nil,    47,    51,    41,    18,    39,
    38,    37,    40,    48,    33,   nil,   nil,    50,   nil,   nil,
   nil,   nil,    64,   nil,    34,    51,   nil,    18,    39,    38,
    37,    40,    47,    33,    41,   nil,   nil,   nil,   nil,   nil,
    48,   nil,   nil,    34,    50,   nil,   nil,   nil,   nil,    64,
   nil,    47,    51,    41,    18,    39,    38,    37,    40,    48,
    33,   nil,   nil,    50,   nil,   nil,   nil,   nil,    64,   nil,
    34,    51,   nil,    18,    39,    38,    37,    40,    47,    33,
    41,   nil,   nil,   nil,   nil,   nil,    48,   nil,   nil,    34,
    50,   nil,   nil,   nil,   nil,    64,   nil,    47,    51,    41,
    18,    39,    38,    37,    40,    48,    33,   nil,   nil,    50,
   nil,   nil,   nil,   nil,    64,   nil,    34,    51,   nil,    18,
    39,    38,    37,    40,    47,    33,    41,   nil,   nil,   nil,
   nil,   nil,    48,   nil,   nil,    34,    50,   nil,   nil,   nil,
   nil,    64,   nil,    47,    51,    41,   nil,   nil,   nil,   nil,
   nil,    48,   153,   nil,   nil,    50,   nil,   nil,   nil,   nil,
    64,   nil,   nil,    51,    18,    39,    38,    37,    40,   nil,
    33,    18,    39,    38,    37,    40,   nil,    33,   nil,   nil,
    34,   nil,   nil,   nil,   nil,   nil,   nil,    34,    47,   nil,
    41,   nil,   nil,   nil,   164,    47,    48,    41,   nil,   nil,
    50,   nil,   nil,    48,   153,    64,   nil,    50,    51,   nil,
   nil,   nil,    64,   nil,   nil,    51,    18,    39,    38,    37,
    40,   nil,    33,    18,    39,    38,    37,    40,   nil,    33,
   nil,   nil,    34,   nil,   nil,   nil,   nil,   nil,   nil,    34,
    47,   nil,    41,   nil,   nil,   nil,   nil,    47,    48,    41,
   nil,   nil,    50,   nil,   nil,    48,   nil,    64,   nil,    50,
    51,   nil,   nil,   nil,    64,   nil,   nil,    51,    18,    39,
    38,    37,    40,   nil,    33,    18,    39,    38,    37,    40,
   nil,    33,   nil,   nil,    34,   nil,   nil,   nil,   nil,   nil,
   nil,    34,    47,   nil,    41,   nil,   nil,   nil,   nil,    47,
    48,    41,   nil,   nil,    50,   nil,   nil,    48,   nil,    64,
   nil,    50,    51,   nil,   nil,   nil,    64,   nil,   nil,    51 ]

racc_action_check = [
    25,     2,     2,     2,     2,     2,    16,     2,    53,   177,
     1,    29,    29,    29,    29,     3,    29,     2,    29,   177,
    88,    19,    53,    88,    20,     2,    25,     2,   128,   128,
   128,   128,   128,     2,   128,     2,     2,     2,     2,     2,
     2,     2,     2,     2,   128,     2,     2,    25,    21,    16,
    26,   128,   128,    27,   128,    22,    22,    22,    22,    22,
   128,    22,   128,   128,   128,   128,   128,   128,   128,   128,
   128,    22,   128,   128,    33,    33,    33,    33,    33,    22,
    33,    22,    35,    28,    35,   141,    62,    22,    48,    35,
    33,    22,    49,    62,    30,    30,    22,    54,    33,    22,
    33,    34,    34,    34,    34,    34,    33,    34,   141,    95,
    33,    95,    31,    31,    31,    33,    95,    34,    33,    56,
    41,    41,    41,    41,    41,    34,    41,    34,   116,   116,
   116,   110,   110,    34,   111,   111,    41,    34,   117,   117,
   117,    58,    34,    59,    41,    34,    41,    47,    47,    47,
    47,    47,    41,    47,   112,   112,    41,   113,   113,   114,
   114,    41,    64,    47,    41,   115,   115,   121,   121,    65,
    66,    47,    47,    47,    50,    50,    50,    50,    50,    47,
    50,    67,    17,    47,    68,    86,    87,    94,    47,    97,
    50,    47,    17,    51,    51,    51,    51,    51,    50,    17,
    50,    98,   109,   109,   109,   109,    50,   109,   101,   109,
    50,   103,   104,   105,   106,    50,   107,    51,    50,    51,
    55,    55,    55,    55,    55,    51,    55,   108,   122,    51,
   127,   131,   136,   137,    51,   139,    55,    51,   140,    57,
    57,    57,    57,    57,    55,    57,    55,   143,   147,   150,
   152,   153,    55,   156,   157,    57,    55,   158,   159,   163,
   165,    55,   173,    57,    55,    57,    69,    69,    69,    69,
    69,    57,    69,   181,   184,    57,   185,   nil,   nil,   nil,
    57,   nil,    69,    57,   nil,    70,    70,    70,    70,    70,
    69,    70,    69,   nil,   nil,   nil,   nil,   nil,    69,   nil,
   nil,    70,    69,   nil,   nil,   nil,   nil,    69,   nil,    70,
    69,    70,    71,    71,    71,    71,    71,    70,    71,   nil,
   nil,    70,   nil,   nil,   nil,   nil,    70,   nil,    71,    70,
   nil,    72,    72,    72,    72,    72,    71,    72,    71,   nil,
   nil,   nil,   nil,   nil,    71,   nil,   nil,    72,    71,   nil,
   nil,   nil,   nil,    71,   nil,    72,    71,    72,    73,    73,
    73,    73,    73,    72,    73,   nil,   nil,    72,   nil,   nil,
   nil,   nil,    72,   nil,    73,    72,   nil,    74,    74,    74,
    74,    74,    73,    74,    73,   nil,   nil,   nil,   nil,   nil,
    73,   nil,   nil,    74,    73,   nil,   nil,   nil,   nil,    73,
   nil,    74,    73,    74,    75,    75,    75,    75,    75,    74,
    75,   nil,   nil,    74,   nil,   nil,   nil,   nil,    74,   nil,
    75,    74,   nil,    76,    76,    76,    76,    76,    75,    76,
    75,   nil,   nil,   nil,   nil,   nil,    75,   nil,   nil,    76,
    75,   nil,   nil,   nil,   nil,    75,   nil,    76,    75,    76,
    77,    77,    77,    77,    77,    76,    77,   nil,   nil,    76,
   nil,   nil,   nil,   nil,    76,   nil,    77,    76,   nil,    78,
    78,    78,    78,    78,    77,    78,    77,   nil,   nil,   nil,
   nil,   nil,    77,   nil,   nil,    78,    77,   nil,   nil,   nil,
   nil,    77,   nil,    78,    77,    78,    79,    79,    79,    79,
    79,    78,    79,   nil,   nil,    78,   nil,   nil,   nil,   nil,
    78,   nil,    79,    78,   nil,    80,    80,    80,    80,    80,
    79,    80,    79,   nil,   nil,   nil,   nil,   nil,    79,   nil,
   nil,    80,    79,   nil,   nil,   nil,   nil,    79,   nil,    80,
    79,    80,    81,    81,    81,    81,    81,    80,    81,   nil,
   nil,    80,   nil,   nil,   nil,   nil,    80,   nil,    81,    80,
   nil,    84,    84,    84,    84,    84,    81,    84,    81,   nil,
   nil,   nil,   nil,   nil,    81,   nil,   nil,    84,    81,   nil,
   nil,   nil,   nil,    81,   nil,    84,    81,    84,    85,    85,
    85,    85,    85,    84,    85,   nil,   nil,    84,   nil,   nil,
   nil,   nil,    84,   nil,    85,    84,   nil,    91,    91,    91,
    91,    91,    85,    91,    85,   nil,   nil,   nil,   nil,   nil,
    85,   nil,   nil,    91,    85,   nil,   nil,   nil,   nil,    85,
   nil,    91,    85,    91,    96,    96,    96,    96,    96,    91,
    96,   nil,   nil,    91,   nil,   nil,   nil,   nil,    91,   nil,
    96,    91,   nil,   102,   102,   102,   102,   102,    96,   102,
    96,   nil,   nil,   nil,   nil,   nil,    96,   nil,   nil,   102,
    96,   nil,   nil,   nil,   nil,    96,   nil,   102,    96,   102,
   126,   126,   126,   126,   126,   102,   126,   nil,   nil,   102,
   nil,   nil,   nil,   nil,   102,   nil,   126,   102,   nil,   129,
   129,   129,   129,   129,   126,   129,   126,   nil,   nil,   nil,
   nil,   nil,   126,   nil,   nil,   129,   126,   nil,   nil,   nil,
   nil,   126,   nil,   129,   126,   129,   nil,   nil,   nil,   nil,
   nil,   129,   129,   nil,   nil,   129,   nil,   nil,   nil,   nil,
   129,   nil,   nil,   129,   132,   132,   132,   132,   132,   nil,
   132,   149,   149,   149,   149,   149,   nil,   149,   nil,   nil,
   132,   nil,   nil,   nil,   nil,   nil,   nil,   149,   132,   nil,
   132,   nil,   nil,   nil,   149,   149,   132,   149,   nil,   nil,
   132,   nil,   nil,   149,   149,   132,   nil,   149,   132,   nil,
   nil,   nil,   149,   nil,   nil,   149,   154,   154,   154,   154,
   154,   nil,   154,   162,   162,   162,   162,   162,   nil,   162,
   nil,   nil,   154,   nil,   nil,   nil,   nil,   nil,   nil,   162,
   154,   nil,   154,   nil,   nil,   nil,   nil,   162,   154,   162,
   nil,   nil,   154,   nil,   nil,   162,   nil,   154,   nil,   162,
   154,   nil,   nil,   nil,   162,   nil,   nil,   162,   168,   168,
   168,   168,   168,   nil,   168,   169,   169,   169,   169,   169,
   nil,   169,   nil,   nil,   168,   nil,   nil,   nil,   nil,   nil,
   nil,   169,   168,   nil,   168,   nil,   nil,   nil,   nil,   169,
   168,   169,   nil,   nil,   168,   nil,   nil,   169,   nil,   168,
   nil,   169,   168,   nil,   nil,   nil,   169,   nil,   nil,   169 ]

racc_action_pointer = [
   nil,    10,    -2,    15,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,   165,   nil,    18,
    21,    45,    52,   nil,   nil,    -3,    47,    31,    62,    -2,
    86,   102,   nil,    71,    98,    55,   nil,   nil,   nil,   nil,
   nil,   117,   nil,   nil,   nil,   nil,   nil,   144,    59,    67,
   171,   190,   nil,    -9,    94,   217,   116,   236,   124,   109,
   nil,   nil,    59,   nil,   112,   140,   167,   152,   159,   263,
   282,   309,   328,   355,   374,   401,   420,   447,   466,   493,
   512,   539,   nil,   nil,   558,   585,   182,   156,    -8,   nil,
   nil,   604,   nil,   nil,   162,    82,   631,   186,   184,   nil,
   nil,   180,   650,   208,   209,   210,   211,   213,   206,   189,
   123,   126,   146,   149,   151,   157,   118,   128,   nil,   nil,
   nil,   137,   200,   nil,   nil,   nil,   677,   200,    25,   696,
   nil,   214,   741,   nil,   nil,   nil,   202,   202,   nil,   205,
   208,    82,   nil,   230,   nil,   nil,   nil,   223,   nil,   748,
   223,   nil,   201,   202,   793,   nil,   228,   251,   254,   233,
   nil,   nil,   800,   223,   nil,   234,   nil,   nil,   845,   852,
   nil,   nil,   nil,   233,   nil,   nil,   nil,   -16,   nil,   nil,
   nil,   270,   nil,   nil,   244,   251,   nil ]

racc_action_default = [
    -2,   -96,    -1,   -96,    -3,    -4,    -5,    -6,    -7,    -8,
    -9,   -10,   -11,   -12,   -13,   -14,   -96,   -64,   -19,   -96,
   -96,   -96,   -96,   -28,   -29,   -96,   -96,   -41,   -42,   -44,
   -46,   -53,   -56,   -96,   -96,   -62,   -63,   -68,   -69,   -70,
   -71,   -96,   -73,   -74,   -75,   -76,   -77,   -96,   -96,   -96,
   -96,   -96,   187,   -96,   -96,   -96,   -96,   -96,   -96,   -23,
   -25,   -24,   -64,   -27,   -96,   -96,   -96,   -96,   -96,   -96,
   -96,   -96,   -96,   -96,   -96,   -96,   -96,   -96,   -96,   -96,
   -96,   -96,   -60,   -61,   -96,   -96,   -96,   -96,   -96,   -79,
   -80,   -96,    -2,   -86,   -96,   -94,   -96,   -96,   -96,   -18,
   -20,   -96,   -96,   -96,   -32,   -96,   -32,   -96,   -43,   -45,
   -47,   -48,   -49,   -50,   -51,   -52,   -54,   -55,   -57,   -58,
   -59,   -96,   -96,   -67,   -72,   -78,   -96,   -96,   -96,   -96,
   -15,   -96,   -96,   -21,   -22,   -26,   -96,   -33,   -34,   -96,
   -96,   -96,   -37,   -96,   -65,   -66,   -81,   -96,   -40,   -96,
   -96,   -90,   -96,   -96,   -96,   -16,   -96,   -96,   -96,   -96,
   -36,   -38,   -96,   -85,   -87,   -96,   -91,   -89,   -96,   -96,
   -17,   -30,   -35,   -96,   -95,   -39,   -82,   -96,   -88,   -92,
   -93,   -32,   -83,   -84,   -96,   -96,   -31 ]

racc_goto_table = [
    63,    93,    17,     2,   136,    88,   140,    82,    83,   142,
   150,   151,   110,   111,   112,   113,   114,   115,     1,    87,
   116,   117,    59,   141,   108,    90,   109,    95,    94,   183,
   165,   166,   176,    99,   149,   101,   nil,   nil,   nil,   nil,
   nil,   nil,   121,   161,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   118,   119,   120,   nil,   nil,   nil,   nil,
   nil,   nil,    90,   122,   nil,   nil,   nil,   nil,   nil,   127,
   nil,   nil,   nil,   nil,   130,   nil,   nil,   nil,   nil,   nil,
   134,   184,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   128,   nil,   nil,   nil,   163,
   nil,   nil,   nil,   nil,   146,   nil,   nil,   152,   171,   nil,
   155,   174,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   152,    17,   182,
   nil,   nil,   170,   nil,   nil,   nil,   nil,   186,   nil,   nil,
   175,   nil,   nil,   nil,   nil,   nil,   179,   180 ]

racc_goto_check = [
    15,    19,    16,     2,    18,    31,    18,    28,    28,    22,
    39,    40,    26,    26,    26,    26,    26,    26,     1,    15,
    27,    27,    17,    21,    24,    15,    25,    29,    15,    33,
    39,    40,    37,    15,    38,    15,   nil,   nil,   nil,   nil,
   nil,   nil,    31,    22,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    28,    28,    28,   nil,   nil,   nil,   nil,
   nil,   nil,    15,    15,   nil,   nil,   nil,   nil,   nil,    15,
   nil,   nil,   nil,   nil,    15,   nil,   nil,   nil,   nil,   nil,
    15,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,    19,
   nil,   nil,   nil,   nil,    15,   nil,   nil,    15,    19,   nil,
    15,    19,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    15,    16,    19,
   nil,   nil,    15,   nil,   nil,   nil,   nil,    19,   nil,   nil,
    15,   nil,   nil,   nil,   nil,   nil,    15,    15 ]

racc_goto_pointer = [
   nil,    18,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   -22,     0,     2,  -100,   -48,
   nil,   -84,   -98,   nil,   -45,   -44,   -59,   -57,   -26,   -24,
   nil,   -42,   nil,  -148,   nil,   nil,   nil,  -131,   -95,  -119,
  -118 ]

racc_goto_default = [
   nil,   nil,   nil,     4,     5,     6,     7,     8,     9,    10,
    11,    12,    13,    14,    15,    24,    62,   nil,   nil,   nil,
   137,   nil,   nil,    27,    28,    29,    30,    31,    32,    35,
    36,   nil,    42,    43,    44,    45,    46,   nil,   nil,   nil,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 54, :_reduce_1,
  0, 55, :_reduce_2,
  2, 55, :_reduce_3,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  1, 56, :_reduce_none,
  4, 57, :_reduce_15,
  5, 57, :_reduce_16,
  6, 57, :_reduce_17,
  3, 58, :_reduce_18,
  1, 69, :_reduce_19,
  3, 69, :_reduce_20,
  4, 69, :_reduce_21,
  4, 59, :_reduce_22,
  2, 62, :_reduce_23,
  2, 63, :_reduce_24,
  1, 70, :_reduce_25,
  3, 70, :_reduce_26,
  2, 64, :_reduce_27,
  1, 65, :_reduce_28,
  1, 67, :_reduce_29,
  6, 60, :_reduce_30,
  10, 60, :_reduce_31,
  0, 71, :_reduce_32,
  1, 71, :_reduce_33,
  1, 73, :_reduce_34,
  3, 73, :_reduce_35,
  5, 61, :_reduce_36,
  1, 74, :_reduce_37,
  2, 74, :_reduce_38,
  3, 75, :_reduce_39,
  3, 72, :_reduce_40,
  1, 68, :_reduce_41,
  1, 76, :_reduce_none,
  3, 76, :_reduce_43,
  1, 77, :_reduce_none,
  3, 77, :_reduce_45,
  1, 78, :_reduce_none,
  3, 78, :_reduce_47,
  3, 78, :_reduce_48,
  3, 78, :_reduce_49,
  3, 78, :_reduce_50,
  3, 78, :_reduce_51,
  3, 78, :_reduce_52,
  1, 79, :_reduce_none,
  3, 79, :_reduce_54,
  3, 79, :_reduce_55,
  1, 80, :_reduce_none,
  3, 80, :_reduce_57,
  3, 80, :_reduce_58,
  3, 80, :_reduce_59,
  2, 81, :_reduce_60,
  2, 81, :_reduce_61,
  1, 81, :_reduce_none,
  1, 82, :_reduce_none,
  1, 82, :_reduce_none,
  4, 82, :_reduce_65,
  4, 82, :_reduce_66,
  3, 82, :_reduce_67,
  1, 83, :_reduce_68,
  1, 83, :_reduce_69,
  1, 83, :_reduce_70,
  1, 83, :_reduce_71,
  3, 83, :_reduce_72,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  3, 85, :_reduce_78,
  2, 85, :_reduce_79,
  1, 84, :_reduce_80,
  3, 84, :_reduce_81,
  6, 86, :_reduce_82,
  2, 90, :_reduce_83,
  2, 90, :_reduce_84,
  0, 90, :_reduce_85,
  2, 66, :_reduce_86,
  5, 87, :_reduce_87,
  6, 87, :_reduce_88,
  5, 87, :_reduce_89,
  1, 91, :_reduce_90,
  2, 91, :_reduce_91,
  3, 93, :_reduce_92,
  3, 92, :_reduce_93,
  2, 88, :_reduce_94,
  6, 89, :_reduce_95 ]

racc_reduce_n = 96

racc_shift_n = 187

racc_token_table = {
  false => 0,
  :error => 1,
  :ILLEGAL => 2,
  :IDENTIFIER => 3,
  :STRING => 4,
  :FLOAT => 5,
  :INT => 6,
  :BOOL => 7,
  :PLUS => 8,
  :MINUS => 9,
  :STAR => 10,
  :SLASH => 11,
  :MODULO => 12,
  :GREATER => 13,
  :GREATEREQ => 14,
  :LESS => 15,
  :LESSEQ => 16,
  :EQUAL => 17,
  :EQUALEQ => 18,
  :BANG => 19,
  :BANGEQ => 20,
  :AND => 21,
  :OR => 22,
  :NOT => 23,
  :PIPE => 24,
  :LBRACE => 25,
  :RBRACE => 26,
  :LSQUARE => 27,
  :RSQUARE => 28,
  :LPAREN => 29,
  :RPAREN => 30,
  :COMMA => 31,
  :COLON => 32,
  :SEMI => 33,
  :DOT => 34,
  :IF => 35,
  :ELSE => 36,
  :LOOP => 37,
  :LEAVE => 38,
  :SWITCH => 39,
  :PACKAGE => 40,
  :IMPORT => 41,
  :CONST => 42,
  :DATA => 43,
  :FUN => 44,
  :LET => 45,
  :MUT => 46,
  :TRY => 47,
  :RETURN => 48,
  :EQARROW => 49,
  :ARROW => 50,
  :EOF => 51,
  :UMINUS => 52 }

racc_nt_base = 53

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "ILLEGAL",
  "IDENTIFIER",
  "STRING",
  "FLOAT",
  "INT",
  "BOOL",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "MODULO",
  "GREATER",
  "GREATEREQ",
  "LESS",
  "LESSEQ",
  "EQUAL",
  "EQUALEQ",
  "BANG",
  "BANGEQ",
  "AND",
  "OR",
  "NOT",
  "PIPE",
  "LBRACE",
  "RBRACE",
  "LSQUARE",
  "RSQUARE",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "COLON",
  "SEMI",
  "DOT",
  "IF",
  "ELSE",
  "LOOP",
  "LEAVE",
  "SWITCH",
  "PACKAGE",
  "IMPORT",
  "CONST",
  "DATA",
  "FUN",
  "LET",
  "MUT",
  "TRY",
  "RETURN",
  "EQARROW",
  "ARROW",
  "EOF",
  "UMINUS",
  "$start",
  "program",
  "stmt_list",
  "stmt",
  "let_stmt",
  "assign_stmt",
  "const_stmt",
  "fun_def",
  "data_def",
  "import_stmt",
  "package_stmt",
  "return_stmt",
  "leave_stmt",
  "loop_stmt",
  "expr_stmt",
  "expr",
  "lvalue",
  "path",
  "params",
  "block",
  "param_list",
  "field_list",
  "field",
  "or_expr",
  "and_expr",
  "cmp_expr",
  "add_expr",
  "mul_expr",
  "unary_expr",
  "postfix_expr",
  "primary",
  "args",
  "list_lit",
  "if_expr",
  "switch_expr",
  "try_expr",
  "fun_lit",
  "else_clause",
  "switch_body",
  "else_arm",
  "switch_arm" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_1(val, _values, result)
          first = val[0].first
      last  = val[0].last
      result = AST::Program.new(val[0],
        first ? first.start : nil,
        last  ? last.end   : nil)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_2(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_3(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_15(val, _values, result)
     result = AST::Let.new(val[1].lexeme, val[3], false,
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_16(val, _values, result)
     result = AST::Let.new(val[2].lexeme, val[4], true,
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_17(val, _values, result)
     result = AST::LetDestructure.new(val[1].lexeme, val[3].lexeme, val[5],
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_18(val, _values, result)
     result = AST::Assign.new(val[0], val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_19(val, _values, result)
     result = AST::Identifier.new(val[0].lexeme,
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_20(val, _values, result)
     result = AST::MemberAccess.new(val[0], val[2].lexeme,
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_21(val, _values, result)
     result = AST::Index.new(val[0], val[2],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_22(val, _values, result)
     result = AST::Const.new(val[1].lexeme, val[3],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_23(val, _values, result)
     result = AST::Import.new(val[1],
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 82)
  def _reduce_24(val, _values, result)
     result = AST::Package.new(val[1].lexeme,
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_25(val, _values, result)
     result = val[0].lexeme
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 86)
  def _reduce_26(val, _values, result)
     result = val[0] + '.' + val[2].lexeme
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_27(val, _values, result)
     result = AST::Return.new(val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_28(val, _values, result)
     result = AST::Leave.new(val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_29(val, _values, result)
     result = AST::ExprStmt.new(val[0],
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 100)
  def _reduce_30(val, _values, result)
     result = AST::FunDef.new(val[1].lexeme, val[3], val[5], nil,
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 104)
  def _reduce_31(val, _values, result)
     result = AST::FunDef.new(val[5].lexeme, val[8], val[10],
        AST::Receiver.new(val[2].lexeme, val[3].lexeme,
          val[1].start, val[4].end),
        val[0].start, val[10].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_32(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 110)
  def _reduce_33(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 112)
  def _reduce_34(val, _values, result)
     result = [val[0].lexeme]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 113)
  def _reduce_35(val, _values, result)
     val[0] << val[2].lexeme; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_36(val, _values, result)
     result = AST::DataDef.new(val[1].lexeme, val[3],
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 119)
  def _reduce_37(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_38(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_39(val, _values, result)
     result = AST::Field.new(val[0].lexeme, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 127)
  def _reduce_40(val, _values, result)
     result = AST::Block.new(val[1],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 130)
  def _reduce_41(val, _values, result)
     result = val[0]
    result
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_43(val, _values, result)
     result = AST::BinaryOp.new(val[0], :or, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 44 omitted

module_eval(<<'.,.,', 'parser.y', 139)
  def _reduce_45(val, _values, result)
     result = AST::BinaryOp.new(val[0], :and, val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 46 omitted

module_eval(<<'.,.,', 'parser.y', 144)
  def _reduce_47(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'==', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 147)
  def _reduce_48(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'!=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 150)
  def _reduce_49(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'>', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 153)
  def _reduce_50(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'>=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 156)
  def _reduce_51(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'<', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 159)
  def _reduce_52(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'<=', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 53 omitted

module_eval(<<'.,.,', 'parser.y', 164)
  def _reduce_54(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'+', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 167)
  def _reduce_55(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'-', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

# reduce 56 omitted

module_eval(<<'.,.,', 'parser.y', 172)
  def _reduce_57(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'*', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 175)
  def _reduce_58(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'/', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 178)
  def _reduce_59(val, _values, result)
     result = AST::BinaryOp.new(val[0], :'%', val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 182)
  def _reduce_60(val, _values, result)
     result = AST::UnaryOp.new(:'-', val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 185)
  def _reduce_61(val, _values, result)
     result = AST::UnaryOp.new(:'!', val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

module_eval(<<'.,.,', 'parser.y', 192)
  def _reduce_65(val, _values, result)
     result = AST::Call.new(val[0], val[2],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 195)
  def _reduce_66(val, _values, result)
     result = AST::Index.new(val[0], val[2],
        val[0].start, val[3].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 198)
  def _reduce_67(val, _values, result)
     result = AST::MemberAccess.new(val[0], val[2].lexeme,
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 202)
  def _reduce_68(val, _values, result)
     result = AST::IntLit.new(parse_int(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 205)
  def _reduce_69(val, _values, result)
     result = AST::FloatLit.new(parse_float(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 208)
  def _reduce_70(val, _values, result)
     result = AST::StringLit.new(parse_string(val[0]),
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 211)
  def _reduce_71(val, _values, result)
     result = AST::BoolLit.new(val[0].lexeme == 'True',
        val[0].start, val[0].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 214)
  def _reduce_72(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

module_eval(<<'.,.,', 'parser.y', 222)
  def _reduce_78(val, _values, result)
     result = AST::ListLit.new(val[1],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 225)
  def _reduce_79(val, _values, result)
     result = AST::ListLit.new([],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 228)
  def _reduce_80(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 229)
  def _reduce_81(val, _values, result)
     val[0] << val[2]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_82(val, _values, result)
     result = AST::If.new(val[2], val[4], val[5],
        val[0].start, val[5] ? val[5].end : val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 235)
  def _reduce_83(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 236)
  def _reduce_84(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 237)
  def _reduce_85(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 240)
  def _reduce_86(val, _values, result)
     result = AST::Loop.new(val[1], val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 243)
  def _reduce_87(val, _values, result)
     result = AST::Switch.new(val[1], val[3], nil,
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 246)
  def _reduce_88(val, _values, result)
     result = AST::Switch.new(val[1], val[3], val[4],
        val[0].start, val[5].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 249)
  def _reduce_89(val, _values, result)
     result = AST::Switch.new(val[1], [], val[3],
        val[0].start, val[4].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 252)
  def _reduce_90(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 253)
  def _reduce_91(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 256)
  def _reduce_92(val, _values, result)
     result = AST::SwitchArm.new(val[0], val[2],
        val[0].start, val[2].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 259)
  def _reduce_93(val, _values, result)
     result = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 262)
  def _reduce_94(val, _values, result)
     result = AST::Try.new(val[1],
        val[0].start, val[1].end)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 266)
  def _reduce_95(val, _values, result)
     result = AST::FunDef.new(nil, val[3], val[5], nil,
        val[0].start, val[5].end)
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Taoism
